/**
 * TWS API error codes and messages.
 * Mirrors: ibapi/errors.py
 */
export declare class CodeMsgPair {
    readonly errorCode: number;
    readonly errorMsg: string;
    constructor(errorCode: number, errorMsg: string);
    code(): number;
    msg(): string;
}
export declare const ALREADY_CONNECTED: CodeMsgPair;
export declare const CONNECT_FAIL: CodeMsgPair;
export declare const UPDATE_TWS: CodeMsgPair;
export declare const NOT_CONNECTED: CodeMsgPair;
export declare const UNKNOWN_ID: CodeMsgPair;
export declare const BAD_LENGTH: CodeMsgPair;
export declare const BAD_MESSAGE: CodeMsgPair;
export declare const FAIL_SEND_REQMKT: CodeMsgPair;
export declare const FAIL_SEND_CANMKT: CodeMsgPair;
export declare const FAIL_SEND_ORDER: CodeMsgPair;
export declare const FAIL_SEND_ACCT: CodeMsgPair;
export declare const FAIL_SEND_EXEC: CodeMsgPair;
export declare const FAIL_SEND_CORDER: CodeMsgPair;
export declare const FAIL_SEND_OORDER: CodeMsgPair;
export declare const FAIL_SEND_REQCONTRACT: CodeMsgPair;
export declare const FAIL_SEND_REQMKTDEPTH: CodeMsgPair;
export declare const FAIL_CREATE_SOCK: CodeMsgPair;
export declare const FAIL_SEND_SERVER_LOG_LEVEL: CodeMsgPair;
export declare const FAIL_SEND_FA_REQUEST: CodeMsgPair;
export declare const FAIL_SEND_FA_REPLACE: CodeMsgPair;
export declare const FAIL_SEND_REQSCANNER: CodeMsgPair;
export declare const FAIL_SEND_CANSCANNER: CodeMsgPair;
export declare const FAIL_SEND_REQSCANNERPARAMETERS: CodeMsgPair;
export declare const FAIL_SEND_REQHISTDATA: CodeMsgPair;
export declare const FAIL_SEND_CANHISTDATA: CodeMsgPair;
export declare const FAIL_SEND_REQRTBARS: CodeMsgPair;
export declare const FAIL_SEND_CANRTBARS: CodeMsgPair;
export declare const FAIL_SEND_REQCURRTIME: CodeMsgPair;
export declare const FAIL_SEND_REQFUNDDATA: CodeMsgPair;
export declare const FAIL_SEND_CANFUNDDATA: CodeMsgPair;
export declare const FAIL_SEND_REQCALCIMPLIEDVOLAT: CodeMsgPair;
export declare const FAIL_SEND_REQCALCOPTIONPRICE: CodeMsgPair;
export declare const FAIL_SEND_CANCALCIMPLIEDVOLAT: CodeMsgPair;
export declare const FAIL_SEND_CANCALCOPTIONPRICE: CodeMsgPair;
export declare const FAIL_SEND_REQGLOBALCANCEL: CodeMsgPair;
export declare const FAIL_SEND_REQMARKETDATATYPE: CodeMsgPair;
export declare const FAIL_SEND_REQPOSITIONS: CodeMsgPair;
export declare const FAIL_SEND_CANPOSITIONS: CodeMsgPair;
export declare const FAIL_SEND_REQACCOUNTDATA: CodeMsgPair;
export declare const FAIL_SEND_CANACCOUNTDATA: CodeMsgPair;
export declare const FAIL_SEND_VERIFYREQUEST: CodeMsgPair;
export declare const FAIL_SEND_VERIFYMESSAGE: CodeMsgPair;
export declare const FAIL_SEND_QUERYDISPLAYGROUPS: CodeMsgPair;
export declare const FAIL_SEND_SUBSCRIBETOGROUPEVENTS: CodeMsgPair;
export declare const FAIL_SEND_UPDATEDISPLAYGROUP: CodeMsgPair;
export declare const FAIL_SEND_UNSUBSCRIBEFROMGROUPEVENTS: CodeMsgPair;
export declare const FAIL_SEND_STARTAPI: CodeMsgPair;
export declare const FAIL_SEND_VERIFYANDAUTHREQUEST: CodeMsgPair;
export declare const FAIL_SEND_VERIFYANDAUTHMESSAGE: CodeMsgPair;
export declare const FAIL_SEND_REQPOSITIONSMULTI: CodeMsgPair;
export declare const FAIL_SEND_CANPOSITIONSMULTI: CodeMsgPair;
export declare const FAIL_SEND_REQACCOUNTUPDATESMULTI: CodeMsgPair;
export declare const FAIL_SEND_CANACCOUNTUPDATESMULTI: CodeMsgPair;
export declare const FAIL_SEND_REQSECDEFOPTPARAMS: CodeMsgPair;
export declare const FAIL_SEND_REQSOFTDOLLARTIERS: CodeMsgPair;
export declare const FAIL_SEND_REQFAMILYCODES: CodeMsgPair;
export declare const FAIL_SEND_REQMATCHINGSYMBOLS: CodeMsgPair;
export declare const FAIL_SEND_REQMKTDEPTHEXCHANGES: CodeMsgPair;
export declare const FAIL_SEND_REQSMARTCOMPONENTS: CodeMsgPair;
export declare const FAIL_SEND_REQNEWSPROVIDERS: CodeMsgPair;
export declare const FAIL_SEND_REQNEWSARTICLE: CodeMsgPair;
export declare const FAIL_SEND_REQHISTORICALNEWS: CodeMsgPair;
export declare const FAIL_SEND_REQHEADTIMESTAMP: CodeMsgPair;
export declare const FAIL_SEND_REQHISTOGRAMDATA: CodeMsgPair;
export declare const FAIL_SEND_CANCELHISTOGRAMDATA: CodeMsgPair;
export declare const FAIL_SEND_CANCELHEADTIMESTAMP: CodeMsgPair;
export declare const FAIL_SEND_REQMARKETRULE: CodeMsgPair;
export declare const FAIL_SEND_REQPNL: CodeMsgPair;
export declare const FAIL_SEND_CANCELPNL: CodeMsgPair;
export declare const FAIL_SEND_REQPNLSINGLE: CodeMsgPair;
export declare const FAIL_SEND_CANCELPNLSINGLE: CodeMsgPair;
export declare const FAIL_SEND_REQHISTORICALTICKS: CodeMsgPair;
export declare const FAIL_SEND_REQTICKBYTICKDATA: CodeMsgPair;
export declare const FAIL_SEND_CANCELTICKBYTICKDATA: CodeMsgPair;
export declare const FAIL_SEND_REQCOMPLETEDORDERS: CodeMsgPair;
export declare const INVALID_SYMBOL: CodeMsgPair;
export declare const FAIL_SEND_REQ_WSH_META_DATA: CodeMsgPair;
export declare const FAIL_SEND_CAN_WSH_META_DATA: CodeMsgPair;
export declare const FAIL_SEND_REQ_WSH_EVENT_DATA: CodeMsgPair;
export declare const FAIL_SEND_CAN_WSH_EVENT_DATA: CodeMsgPair;
export declare const FAIL_SEND_REQ_USER_INFO: CodeMsgPair;
export declare const FA_PROFILE_NOT_SUPPORTED: CodeMsgPair;
export declare const FAIL_SEND_REQCURRTIMEINMILLIS: CodeMsgPair;
export declare const ERROR_ENCODING_PROTOBUF: CodeMsgPair;
export declare const FAIL_SEND_CANMKTDEPTH: CodeMsgPair;
export declare const FAIL_SEND_CANCEL_CONTRACT_DATA: CodeMsgPair;
export declare const FAIL_SEND_CANCEL_HISTORICAL_TICKS: CodeMsgPair;
export declare const FAIL_SEND_REQCONFIG: CodeMsgPair;
export declare const FAIL_SEND_UPDATECONFIG: CodeMsgPair;
