/**
 * Mirrors: ibapi/orderdecoder.py
 */
import { Contract } from './contract.js';
import { Order } from './order.js';
import { OrderState } from './order-state.js';
export declare class OrderDecoder {
    contract: Contract;
    order: Order;
    orderState: OrderState;
    version: number;
    serverVersion: number;
    constructor(contract: Contract, order: Order, orderState: OrderState, version: number, serverVersion: number);
    decodeOrderId(fields: Iterator<string>): void;
    decodeContractFields(fields: Iterator<string>): void;
    decodeAction(fields: Iterator<string>): void;
    decodeTotalQuantity(fields: Iterator<string>): void;
    decodeOrderType(fields: Iterator<string>): void;
    decodeLmtPrice(fields: Iterator<string>): void;
    decodeAuxPrice(fields: Iterator<string>): void;
    decodeTIF(fields: Iterator<string>): void;
    decodeOcaGroup(fields: Iterator<string>): void;
    decodeAccount(fields: Iterator<string>): void;
    decodeOpenClose(fields: Iterator<string>): void;
    decodeOrigin(fields: Iterator<string>): void;
    decodeOrderRef(fields: Iterator<string>): void;
    decodeClientId(fields: Iterator<string>): void;
    decodePermId(fields: Iterator<string>): void;
    decodeOutsideRth(fields: Iterator<string>): void;
    decodeHidden(fields: Iterator<string>): void;
    decodeDiscretionaryAmt(fields: Iterator<string>): void;
    decodeGoodAfterTime(fields: Iterator<string>): void;
    skipSharesAllocation(fields: Iterator<string>): void;
    decodeFAParams(fields: Iterator<string>): void;
    decodeModelCode(fields: Iterator<string>): void;
    decodeGoodTillDate(fields: Iterator<string>): void;
    decodeRule80A(fields: Iterator<string>): void;
    decodePercentOffset(fields: Iterator<string>): void;
    decodeSettlingFirm(fields: Iterator<string>): void;
    decodeShortSaleParams(fields: Iterator<string>): void;
    decodeAuctionStrategy(fields: Iterator<string>): void;
    decodeBoxOrderParams(fields: Iterator<string>): void;
    decodePegToStkOrVolOrderParams(fields: Iterator<string>): void;
    decodeDisplaySize(fields: Iterator<string>): void;
    decodeBlockOrder(fields: Iterator<string>): void;
    decodeSweepToFill(fields: Iterator<string>): void;
    decodeAllOrNone(fields: Iterator<string>): void;
    decodeMinQty(fields: Iterator<string>): void;
    decodeOcaType(fields: Iterator<string>): void;
    skipETradeOnly(fields: Iterator<string>): void;
    skipFirmQuoteOnly(fields: Iterator<string>): void;
    skipNbboPriceCap(fields: Iterator<string>): void;
    decodeParentId(fields: Iterator<string>): void;
    decodeTriggerMethod(fields: Iterator<string>): void;
    decodeVolOrderParams(fields: Iterator<string>, readOpenOrderAttribs: boolean): void;
    decodeTrailParams(fields: Iterator<string>): void;
    decodeBasisPoints(fields: Iterator<string>): void;
    decodeComboLegs(fields: Iterator<string>): void;
    decodeSmartComboRoutingParams(fields: Iterator<string>): void;
    decodeScaleOrderParams(fields: Iterator<string>): void;
    decodeHedgeParams(fields: Iterator<string>): void;
    decodeOptOutSmartRouting(fields: Iterator<string>): void;
    decodeClearingParams(fields: Iterator<string>): void;
    decodeNotHeld(fields: Iterator<string>): void;
    decodeDeltaNeutral(fields: Iterator<string>): void;
    decodeAlgoParams(fields: Iterator<string>): void;
    decodeSolicited(fields: Iterator<string>): void;
    decodeOrderStatus(fields: Iterator<string>): void;
    decodeWhatIfInfoAndCommissionAndFees(fields: Iterator<string>): void;
    decodeVolRandomizeFlags(fields: Iterator<string>): void;
    decodePegToBenchParams(fields: Iterator<string>): void;
    decodeConditions(fields: Iterator<string>): void;
    decodeAdjustedOrderParams(fields: Iterator<string>): void;
    decodeStopPriceAndLmtPriceOffset(fields: Iterator<string>): void;
    decodeSoftDollarTier(fields: Iterator<string>): void;
    decodeCashQty(fields: Iterator<string>): void;
    decodeDontUseAutoPriceForHedge(fields: Iterator<string>): void;
    decodeIsOmsContainers(fields: Iterator<string>): void;
    decodeDiscretionaryUpToLimitPrice(fields: Iterator<string>): void;
    decodeAutoCancelDate(fields: Iterator<string>): void;
    decodeFilledQuantity(fields: Iterator<string>): void;
    decodeRefFuturesConId(fields: Iterator<string>): void;
    decodeAutoCancelParent(fields: Iterator<string>, minVersionAutoCancelParent?: number): void;
    decodeShareholder(fields: Iterator<string>): void;
    decodeImbalanceOnly(fields: Iterator<string>, minVersionImbalanceOnly?: number): void;
    decodeRouteMarketableToBbo(fields: Iterator<string>): void;
    decodeParentPermId(fields: Iterator<string>): void;
    decodeCompletedTime(fields: Iterator<string>): void;
    decodeCompletedStatus(fields: Iterator<string>): void;
    decodeUsePriceMgmtAlgo(fields: Iterator<string>): void;
    decodeDuration(fields: Iterator<string>): void;
    decodePostToAts(fields: Iterator<string>): void;
    decodePegBestPegMidOrderAttributes(fields: Iterator<string>): void;
    decodeCustomerAccount(fields: Iterator<string>): void;
    decodeProfessionalCustomer(fields: Iterator<string>): void;
    decodeBondAccruedInterest(fields: Iterator<string>): void;
    decodeIncludeOvernight(fields: Iterator<string>): void;
    decodeCMETaggingFields(fields: Iterator<string>): void;
    decodeSubmitter(fields: Iterator<string>): void;
}
