/**
 * Mirrors: ibapi/order.py
 */
import Decimal from 'decimal.js';
import { SoftDollarTier } from './softdollartier.js';
import type { TagValueList } from './tag-value.js';
import type { OrderCondition } from './order-condition.js';
export declare const CUSTOMER = 0;
export declare const FIRM = 1;
export declare const UNKNOWN = 2;
export declare const AUCTION_UNSET = 0;
export declare const AUCTION_MATCH = 1;
export declare const AUCTION_IMPROVEMENT = 2;
export declare const AUCTION_TRANSPARENT = 3;
export declare const COMPETE_AGAINST_BEST_OFFSET_UP_TO_MID: number;
export declare class OrderComboLeg {
    price: number;
    toString(): string;
}
export declare class Order {
    softDollarTier: SoftDollarTier;
    orderId: number;
    clientId: number;
    permId: number;
    action: string;
    totalQuantity: Decimal;
    orderType: string;
    lmtPrice: Decimal;
    auxPrice: Decimal;
    tif: string;
    activeStartTime: string;
    activeStopTime: string;
    ocaGroup: string;
    ocaType: number;
    orderRef: string;
    transmit: boolean;
    parentId: number;
    blockOrder: boolean;
    sweepToFill: boolean;
    displaySize: number;
    triggerMethod: number;
    outsideRth: boolean;
    hidden: boolean;
    goodAfterTime: string;
    goodTillDate: string;
    rule80A: string;
    allOrNone: boolean;
    minQty: number;
    percentOffset: number;
    overridePercentageConstraints: boolean;
    trailStopPrice: Decimal;
    trailingPercent: Decimal;
    faGroup: string;
    faMethod: string;
    faPercentage: string;
    designatedLocation: string;
    openClose: string;
    origin: number;
    shortSaleSlot: number;
    exemptCode: number;
    discretionaryAmt: number;
    optOutSmartRouting: boolean;
    auctionStrategy: number;
    startingPrice: number;
    stockRefPrice: number;
    delta: number;
    stockRangeLower: number;
    stockRangeUpper: number;
    randomizePrice: boolean;
    randomizeSize: boolean;
    volatility: number;
    volatilityType: number;
    deltaNeutralOrderType: string;
    deltaNeutralAuxPrice: number;
    deltaNeutralConId: number;
    deltaNeutralSettlingFirm: string;
    deltaNeutralClearingAccount: string;
    deltaNeutralClearingIntent: string;
    deltaNeutralOpenClose: string;
    deltaNeutralShortSale: boolean;
    deltaNeutralShortSaleSlot: number;
    deltaNeutralDesignatedLocation: string;
    continuousUpdate: boolean;
    referencePriceType: number;
    basisPoints: number;
    basisPointsType: number;
    scaleInitLevelSize: number;
    scaleSubsLevelSize: number;
    scalePriceIncrement: number;
    scalePriceAdjustValue: number;
    scalePriceAdjustInterval: number;
    scaleProfitOffset: number;
    scaleAutoReset: boolean;
    scaleInitPosition: number;
    scaleInitFillQty: number;
    scaleRandomPercent: boolean;
    scaleTable: string;
    hedgeType: string;
    hedgeParam: string;
    account: string;
    settlingFirm: string;
    clearingAccount: string;
    clearingIntent: string;
    algoStrategy: string;
    algoParams: TagValueList;
    smartComboRoutingParams: TagValueList;
    algoId: string;
    whatIf: boolean;
    notHeld: boolean;
    solicited: boolean;
    modelCode: string;
    orderComboLegs: OrderComboLeg[] | null;
    orderMiscOptions: TagValueList;
    referenceContractId: number;
    peggedChangeAmount: number;
    isPeggedChangeAmountDecrease: boolean;
    referenceChangeAmount: number;
    referenceExchangeId: string;
    adjustedOrderType: string;
    triggerPrice: number;
    adjustedStopPrice: number;
    adjustedStopLimitPrice: number;
    adjustedTrailingAmount: number;
    adjustableTrailingUnit: number;
    lmtPriceOffset: number;
    conditions: OrderCondition[];
    conditionsCancelOrder: boolean;
    conditionsIgnoreRth: boolean;
    extOperator: string;
    cashQty: Decimal;
    mifid2DecisionMaker: string;
    mifid2DecisionAlgo: string;
    mifid2ExecutionTrader: string;
    mifid2ExecutionAlgo: string;
    dontUseAutoPriceForHedge: boolean;
    isOmsContainer: boolean;
    discretionaryUpToLimitPrice: boolean;
    autoCancelDate: string;
    filledQuantity: Decimal;
    refFuturesConId: number;
    autoCancelParent: boolean;
    shareholder: string;
    imbalanceOnly: boolean;
    routeMarketableToBbo: boolean | null;
    parentPermId: number;
    usePriceMgmtAlgo: boolean | null;
    duration: number;
    postToAts: number;
    advancedErrorOverride: string;
    manualOrderTime: string;
    minTradeQty: number;
    minCompeteSize: number;
    competeAgainstBestOffset: number;
    midOffsetAtWhole: number;
    midOffsetAtHalf: number;
    customerAccount: string;
    professionalCustomer: boolean;
    bondAccruedInterest: string;
    includeOvernight: boolean;
    manualOrderIndicator: number;
    submitter: string;
    postOnly: boolean;
    allowPreOpen: boolean;
    ignoreOpenAuction: boolean;
    deactivate: boolean;
    seekPriceImprovement: boolean | null;
    whatIfType: number;
    slOrderId: number;
    slOrderType: string;
    ptOrderId: number;
    ptOrderType: string;
    toString(): string;
}
