/**
 * Equity Info Standard Model.
 * Maps to: openbb_core/provider/standard_models/equity_info.py
 */
import { z } from 'zod';
export declare const EquityInfoQueryParamsSchema: z.ZodObject<{
    symbol: z.ZodEffects<z.ZodString, string, string>;
}, "passthrough", z.ZodTypeAny, z.objectOutputType<{
    symbol: z.ZodEffects<z.ZodString, string, string>;
}, z.ZodTypeAny, "passthrough">, z.objectInputType<{
    symbol: z.ZodEffects<z.ZodString, string, string>;
}, z.ZodTypeAny, "passthrough">>;
export type EquityInfoQueryParams = z.infer<typeof EquityInfoQueryParamsSchema>;
export declare const EquityInfoDataSchema: z.ZodObject<{
    symbol: z.ZodString;
    name: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    cik: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    cusip: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    isin: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    lei: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    legal_name: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    stock_exchange: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    sic: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    short_description: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    long_description: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    ceo: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    company_url: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    business_address: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    mailing_address: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    business_phone_no: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    hq_address1: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    hq_address2: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    hq_address_city: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    hq_address_postal_code: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    hq_state: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    hq_country: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    inc_state: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    inc_country: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    employees: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    entity_legal_form: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    entity_status: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    latest_filing_date: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    irs_number: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    sector: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    industry_category: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    industry_group: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    template: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    standardized_active: z.ZodDefault<z.ZodNullable<z.ZodBoolean>>;
    first_fundamental_date: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    last_fundamental_date: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    first_stock_price_date: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    last_stock_price_date: z.ZodDefault<z.ZodNullable<z.ZodString>>;
}, "passthrough", z.ZodTypeAny, z.objectOutputType<{
    symbol: z.ZodString;
    name: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    cik: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    cusip: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    isin: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    lei: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    legal_name: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    stock_exchange: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    sic: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    short_description: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    long_description: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    ceo: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    company_url: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    business_address: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    mailing_address: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    business_phone_no: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    hq_address1: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    hq_address2: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    hq_address_city: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    hq_address_postal_code: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    hq_state: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    hq_country: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    inc_state: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    inc_country: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    employees: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    entity_legal_form: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    entity_status: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    latest_filing_date: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    irs_number: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    sector: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    industry_category: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    industry_group: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    template: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    standardized_active: z.ZodDefault<z.ZodNullable<z.ZodBoolean>>;
    first_fundamental_date: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    last_fundamental_date: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    first_stock_price_date: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    last_stock_price_date: z.ZodDefault<z.ZodNullable<z.ZodString>>;
}, z.ZodTypeAny, "passthrough">, z.objectInputType<{
    symbol: z.ZodString;
    name: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    cik: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    cusip: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    isin: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    lei: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    legal_name: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    stock_exchange: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    sic: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    short_description: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    long_description: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    ceo: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    company_url: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    business_address: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    mailing_address: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    business_phone_no: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    hq_address1: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    hq_address2: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    hq_address_city: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    hq_address_postal_code: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    hq_state: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    hq_country: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    inc_state: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    inc_country: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    employees: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    entity_legal_form: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    entity_status: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    latest_filing_date: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    irs_number: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    sector: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    industry_category: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    industry_group: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    template: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    standardized_active: z.ZodDefault<z.ZodNullable<z.ZodBoolean>>;
    first_fundamental_date: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    last_fundamental_date: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    first_stock_price_date: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    last_stock_price_date: z.ZodDefault<z.ZodNullable<z.ZodString>>;
}, z.ZodTypeAny, "passthrough">>;
export type EquityInfoData = z.infer<typeof EquityInfoDataSchema>;
