// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: AccountValue.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseAccountValue() {
    return { key: undefined, value: undefined, currency: undefined, accountName: undefined };
}
export const AccountValue = {
    encode(message, writer = new BinaryWriter()) {
        if (message.key !== undefined) {
            writer.uint32(10).string(message.key);
        }
        if (message.value !== undefined) {
            writer.uint32(18).string(message.value);
        }
        if (message.currency !== undefined) {
            writer.uint32(26).string(message.currency);
        }
        if (message.accountName !== undefined) {
            writer.uint32(34).string(message.accountName);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseAccountValue();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.key = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.value = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.currency = reader.string();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.accountName = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            key: isSet(object.key) ? globalThis.String(object.key) : undefined,
            value: isSet(object.value) ? globalThis.String(object.value) : undefined,
            currency: isSet(object.currency) ? globalThis.String(object.currency) : undefined,
            accountName: isSet(object.accountName) ? globalThis.String(object.accountName) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.key !== undefined) {
            obj.key = message.key;
        }
        if (message.value !== undefined) {
            obj.value = message.value;
        }
        if (message.currency !== undefined) {
            obj.currency = message.currency;
        }
        if (message.accountName !== undefined) {
            obj.accountName = message.accountName;
        }
        return obj;
    },
    create(base) {
        return AccountValue.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseAccountValue();
        message.key = object.key ?? undefined;
        message.value = object.value ?? undefined;
        message.currency = object.currency ?? undefined;
        message.accountName = object.accountName ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=AccountValue.js.map