// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: AccountUpdateTime.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseAccountUpdateTime() {
    return { timeStamp: undefined };
}
export const AccountUpdateTime = {
    encode(message, writer = new BinaryWriter()) {
        if (message.timeStamp !== undefined) {
            writer.uint32(10).string(message.timeStamp);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseAccountUpdateTime();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.timeStamp = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { timeStamp: isSet(object.timeStamp) ? globalThis.String(object.timeStamp) : undefined };
    },
    toJSON(message) {
        const obj = {};
        if (message.timeStamp !== undefined) {
            obj.timeStamp = message.timeStamp;
        }
        return obj;
    },
    create(base) {
        return AccountUpdateTime.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseAccountUpdateTime();
        message.timeStamp = object.timeStamp ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=AccountUpdateTime.js.map