// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: AccountSummary.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseAccountSummary() {
    return { reqId: undefined, account: undefined, tag: undefined, value: undefined, currency: undefined };
}
export const AccountSummary = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        if (message.account !== undefined) {
            writer.uint32(18).string(message.account);
        }
        if (message.tag !== undefined) {
            writer.uint32(26).string(message.tag);
        }
        if (message.value !== undefined) {
            writer.uint32(34).string(message.value);
        }
        if (message.currency !== undefined) {
            writer.uint32(42).string(message.currency);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseAccountSummary();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.account = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.tag = reader.string();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.value = reader.string();
                    continue;
                }
                case 5: {
                    if (tag !== 42) {
                        break;
                    }
                    message.currency = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            account: isSet(object.account) ? globalThis.String(object.account) : undefined,
            tag: isSet(object.tag) ? globalThis.String(object.tag) : undefined,
            value: isSet(object.value) ? globalThis.String(object.value) : undefined,
            currency: isSet(object.currency) ? globalThis.String(object.currency) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.account !== undefined) {
            obj.account = message.account;
        }
        if (message.tag !== undefined) {
            obj.tag = message.tag;
        }
        if (message.value !== undefined) {
            obj.value = message.value;
        }
        if (message.currency !== undefined) {
            obj.currency = message.currency;
        }
        return obj;
    },
    create(base) {
        return AccountSummary.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseAccountSummary();
        message.reqId = object.reqId ?? undefined;
        message.account = object.account ?? undefined;
        message.tag = object.tag ?? undefined;
        message.value = object.value ?? undefined;
        message.currency = object.currency ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=AccountSummary.js.map