// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: AccountDataEnd.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseAccountDataEnd() {
    return { accountName: undefined };
}
export const AccountDataEnd = {
    encode(message, writer = new BinaryWriter()) {
        if (message.accountName !== undefined) {
            writer.uint32(10).string(message.accountName);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseAccountDataEnd();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.accountName = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { accountName: isSet(object.accountName) ? globalThis.String(object.accountName) : undefined };
    },
    toJSON(message) {
        const obj = {};
        if (message.accountName !== undefined) {
            obj.accountName = message.accountName;
        }
        return obj;
    },
    create(base) {
        return AccountDataEnd.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseAccountDataEnd();
        message.accountName = object.accountName ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=AccountDataEnd.js.map