// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: AccountDataRequest.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseAccountDataRequest() {
    return { subscribe: undefined, acctCode: undefined };
}
export const AccountDataRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.subscribe !== undefined) {
            writer.uint32(8).bool(message.subscribe);
        }
        if (message.acctCode !== undefined) {
            writer.uint32(18).string(message.acctCode);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseAccountDataRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.subscribe = reader.bool();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.acctCode = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            subscribe: isSet(object.subscribe) ? globalThis.Boolean(object.subscribe) : undefined,
            acctCode: isSet(object.acctCode) ? globalThis.String(object.acctCode) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.subscribe !== undefined) {
            obj.subscribe = message.subscribe;
        }
        if (message.acctCode !== undefined) {
            obj.acctCode = message.acctCode;
        }
        return obj;
    },
    create(base) {
        return AccountDataRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseAccountDataRequest();
        message.subscribe = object.subscribe ?? undefined;
        message.acctCode = object.acctCode ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=AccountDataRequest.js.map