// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: AccountSummaryRequest.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseAccountSummaryRequest() {
    return { reqId: undefined, group: undefined, tags: undefined };
}
export const AccountSummaryRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        if (message.group !== undefined) {
            writer.uint32(18).string(message.group);
        }
        if (message.tags !== undefined) {
            writer.uint32(26).string(message.tags);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseAccountSummaryRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.group = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.tags = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            group: isSet(object.group) ? globalThis.String(object.group) : undefined,
            tags: isSet(object.tags) ? globalThis.String(object.tags) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.group !== undefined) {
            obj.group = message.group;
        }
        if (message.tags !== undefined) {
            obj.tags = message.tags;
        }
        return obj;
    },
    create(base) {
        return AccountSummaryRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseAccountSummaryRequest();
        message.reqId = object.reqId ?? undefined;
        message.group = object.group ?? undefined;
        message.tags = object.tags ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=AccountSummaryRequest.js.map