// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: AccountUpdateMulti.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseAccountUpdateMulti() {
    return {
        reqId: undefined,
        account: undefined,
        modelCode: undefined,
        key: undefined,
        value: undefined,
        currency: undefined,
    };
}
export const AccountUpdateMulti = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        if (message.account !== undefined) {
            writer.uint32(18).string(message.account);
        }
        if (message.modelCode !== undefined) {
            writer.uint32(26).string(message.modelCode);
        }
        if (message.key !== undefined) {
            writer.uint32(34).string(message.key);
        }
        if (message.value !== undefined) {
            writer.uint32(42).string(message.value);
        }
        if (message.currency !== undefined) {
            writer.uint32(50).string(message.currency);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseAccountUpdateMulti();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.account = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.modelCode = reader.string();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.key = reader.string();
                    continue;
                }
                case 5: {
                    if (tag !== 42) {
                        break;
                    }
                    message.value = reader.string();
                    continue;
                }
                case 6: {
                    if (tag !== 50) {
                        break;
                    }
                    message.currency = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            account: isSet(object.account) ? globalThis.String(object.account) : undefined,
            modelCode: isSet(object.modelCode) ? globalThis.String(object.modelCode) : undefined,
            key: isSet(object.key) ? globalThis.String(object.key) : undefined,
            value: isSet(object.value) ? globalThis.String(object.value) : undefined,
            currency: isSet(object.currency) ? globalThis.String(object.currency) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.account !== undefined) {
            obj.account = message.account;
        }
        if (message.modelCode !== undefined) {
            obj.modelCode = message.modelCode;
        }
        if (message.key !== undefined) {
            obj.key = message.key;
        }
        if (message.value !== undefined) {
            obj.value = message.value;
        }
        if (message.currency !== undefined) {
            obj.currency = message.currency;
        }
        return obj;
    },
    create(base) {
        return AccountUpdateMulti.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseAccountUpdateMulti();
        message.reqId = object.reqId ?? undefined;
        message.account = object.account ?? undefined;
        message.modelCode = object.modelCode ?? undefined;
        message.key = object.key ?? undefined;
        message.value = object.value ?? undefined;
        message.currency = object.currency ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=AccountUpdateMulti.js.map