// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: ApiConfig.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { ApiPrecautionsConfig } from "./ApiPrecautionsConfig.js";
import { ApiSettingsConfig } from "./ApiSettingsConfig.js";
export const protobufPackage = "protobuf";
function createBaseApiConfig() {
    return { precautions: undefined, settings: undefined };
}
export const ApiConfig = {
    encode(message, writer = new BinaryWriter()) {
        if (message.precautions !== undefined) {
            ApiPrecautionsConfig.encode(message.precautions, writer.uint32(10).fork()).join();
        }
        if (message.settings !== undefined) {
            ApiSettingsConfig.encode(message.settings, writer.uint32(18).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseApiConfig();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.precautions = ApiPrecautionsConfig.decode(reader, reader.uint32());
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.settings = ApiSettingsConfig.decode(reader, reader.uint32());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            precautions: isSet(object.precautions) ? ApiPrecautionsConfig.fromJSON(object.precautions) : undefined,
            settings: isSet(object.settings) ? ApiSettingsConfig.fromJSON(object.settings) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.precautions !== undefined) {
            obj.precautions = ApiPrecautionsConfig.toJSON(message.precautions);
        }
        if (message.settings !== undefined) {
            obj.settings = ApiSettingsConfig.toJSON(message.settings);
        }
        return obj;
    },
    create(base) {
        return ApiConfig.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseApiConfig();
        message.precautions = (object.precautions !== undefined && object.precautions !== null)
            ? ApiPrecautionsConfig.fromPartial(object.precautions)
            : undefined;
        message.settings = (object.settings !== undefined && object.settings !== null)
            ? ApiSettingsConfig.fromPartial(object.settings)
            : undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=ApiConfig.js.map