// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: AttachedOrders.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseAttachedOrders() {
    return { slOrderId: undefined, slOrderType: undefined, ptOrderId: undefined, ptOrderType: undefined };
}
export const AttachedOrders = {
    encode(message, writer = new BinaryWriter()) {
        if (message.slOrderId !== undefined) {
            writer.uint32(8).int32(message.slOrderId);
        }
        if (message.slOrderType !== undefined) {
            writer.uint32(18).string(message.slOrderType);
        }
        if (message.ptOrderId !== undefined) {
            writer.uint32(24).int32(message.ptOrderId);
        }
        if (message.ptOrderType !== undefined) {
            writer.uint32(34).string(message.ptOrderType);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseAttachedOrders();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.slOrderId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.slOrderType = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 24) {
                        break;
                    }
                    message.ptOrderId = reader.int32();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.ptOrderType = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            slOrderId: isSet(object.slOrderId) ? globalThis.Number(object.slOrderId) : undefined,
            slOrderType: isSet(object.slOrderType) ? globalThis.String(object.slOrderType) : undefined,
            ptOrderId: isSet(object.ptOrderId) ? globalThis.Number(object.ptOrderId) : undefined,
            ptOrderType: isSet(object.ptOrderType) ? globalThis.String(object.ptOrderType) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.slOrderId !== undefined) {
            obj.slOrderId = Math.round(message.slOrderId);
        }
        if (message.slOrderType !== undefined) {
            obj.slOrderType = message.slOrderType;
        }
        if (message.ptOrderId !== undefined) {
            obj.ptOrderId = Math.round(message.ptOrderId);
        }
        if (message.ptOrderType !== undefined) {
            obj.ptOrderType = message.ptOrderType;
        }
        return obj;
    },
    create(base) {
        return AttachedOrders.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseAttachedOrders();
        message.slOrderId = object.slOrderId ?? undefined;
        message.slOrderType = object.slOrderType ?? undefined;
        message.ptOrderId = object.ptOrderId ?? undefined;
        message.ptOrderType = object.ptOrderType ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=AttachedOrders.js.map