// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: AutoOpenOrdersRequest.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseAutoOpenOrdersRequest() {
    return { autoBind: undefined };
}
export const AutoOpenOrdersRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.autoBind !== undefined) {
            writer.uint32(8).bool(message.autoBind);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseAutoOpenOrdersRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.autoBind = reader.bool();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { autoBind: isSet(object.autoBind) ? globalThis.Boolean(object.autoBind) : undefined };
    },
    toJSON(message) {
        const obj = {};
        if (message.autoBind !== undefined) {
            obj.autoBind = message.autoBind;
        }
        return obj;
    },
    create(base) {
        return AutoOpenOrdersRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseAutoOpenOrdersRequest();
        message.autoBind = object.autoBind ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=AutoOpenOrdersRequest.js.map