// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: CalculateOptionPriceRequest.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Contract } from "./Contract.js";
export const protobufPackage = "protobuf";
function createBaseCalculateOptionPriceRequest() {
    return {
        reqId: undefined,
        contract: undefined,
        volatility: undefined,
        underPrice: undefined,
        optionPriceOptions: {},
    };
}
export const CalculateOptionPriceRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        if (message.contract !== undefined) {
            Contract.encode(message.contract, writer.uint32(18).fork()).join();
        }
        if (message.volatility !== undefined) {
            writer.uint32(25).double(message.volatility);
        }
        if (message.underPrice !== undefined) {
            writer.uint32(33).double(message.underPrice);
        }
        globalThis.Object.entries(message.optionPriceOptions).forEach(([key, value]) => {
            CalculateOptionPriceRequest_OptionPriceOptionsEntry.encode({ key: key, value }, writer.uint32(42).fork())
                .join();
        });
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseCalculateOptionPriceRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.contract = Contract.decode(reader, reader.uint32());
                    continue;
                }
                case 3: {
                    if (tag !== 25) {
                        break;
                    }
                    message.volatility = reader.double();
                    continue;
                }
                case 4: {
                    if (tag !== 33) {
                        break;
                    }
                    message.underPrice = reader.double();
                    continue;
                }
                case 5: {
                    if (tag !== 42) {
                        break;
                    }
                    const entry5 = CalculateOptionPriceRequest_OptionPriceOptionsEntry.decode(reader, reader.uint32());
                    if (entry5.value !== undefined) {
                        message.optionPriceOptions[entry5.key] = entry5.value;
                    }
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            contract: isSet(object.contract) ? Contract.fromJSON(object.contract) : undefined,
            volatility: isSet(object.volatility) ? globalThis.Number(object.volatility) : undefined,
            underPrice: isSet(object.underPrice) ? globalThis.Number(object.underPrice) : undefined,
            optionPriceOptions: isObject(object.optionPriceOptions)
                ? globalThis.Object.entries(object.optionPriceOptions).reduce((acc, [key, value]) => {
                    acc[key] = globalThis.String(value);
                    return acc;
                }, {})
                : {},
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.contract !== undefined) {
            obj.contract = Contract.toJSON(message.contract);
        }
        if (message.volatility !== undefined) {
            obj.volatility = message.volatility;
        }
        if (message.underPrice !== undefined) {
            obj.underPrice = message.underPrice;
        }
        if (message.optionPriceOptions) {
            const entries = globalThis.Object.entries(message.optionPriceOptions);
            if (entries.length > 0) {
                obj.optionPriceOptions = {};
                entries.forEach(([k, v]) => {
                    obj.optionPriceOptions[k] = v;
                });
            }
        }
        return obj;
    },
    create(base) {
        return CalculateOptionPriceRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseCalculateOptionPriceRequest();
        message.reqId = object.reqId ?? undefined;
        message.contract = (object.contract !== undefined && object.contract !== null)
            ? Contract.fromPartial(object.contract)
            : undefined;
        message.volatility = object.volatility ?? undefined;
        message.underPrice = object.underPrice ?? undefined;
        message.optionPriceOptions = globalThis.Object.entries(object.optionPriceOptions ?? {})
            .reduce((acc, [key, value]) => {
            if (value !== undefined) {
                acc[key] = globalThis.String(value);
            }
            return acc;
        }, {});
        return message;
    },
};
function createBaseCalculateOptionPriceRequest_OptionPriceOptionsEntry() {
    return { key: "", value: "" };
}
export const CalculateOptionPriceRequest_OptionPriceOptionsEntry = {
    encode(message, writer = new BinaryWriter()) {
        if (message.key !== "") {
            writer.uint32(10).string(message.key);
        }
        if (message.value !== "") {
            writer.uint32(18).string(message.value);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseCalculateOptionPriceRequest_OptionPriceOptionsEntry();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.key = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.value = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            key: isSet(object.key) ? globalThis.String(object.key) : "",
            value: isSet(object.value) ? globalThis.String(object.value) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.key !== "") {
            obj.key = message.key;
        }
        if (message.value !== "") {
            obj.value = message.value;
        }
        return obj;
    },
    create(base) {
        return CalculateOptionPriceRequest_OptionPriceOptionsEntry.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseCalculateOptionPriceRequest_OptionPriceOptionsEntry();
        message.key = object.key ?? "";
        message.value = object.value ?? "";
        return message;
    },
};
function isObject(value) {
    return typeof value === "object" && value !== null;
}
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=CalculateOptionPriceRequest.js.map