// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: CancelMarketDepth.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseCancelMarketDepth() {
    return { reqId: undefined, isSmartDepth: undefined };
}
export const CancelMarketDepth = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        if (message.isSmartDepth !== undefined) {
            writer.uint32(16).bool(message.isSmartDepth);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseCancelMarketDepth();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.isSmartDepth = reader.bool();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            isSmartDepth: isSet(object.isSmartDepth) ? globalThis.Boolean(object.isSmartDepth) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.isSmartDepth !== undefined) {
            obj.isSmartDepth = message.isSmartDepth;
        }
        return obj;
    },
    create(base) {
        return CancelMarketDepth.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseCancelMarketDepth();
        message.reqId = object.reqId ?? undefined;
        message.isSmartDepth = object.isSmartDepth ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=CancelMarketDepth.js.map