// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: CancelOrderRequest.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { OrderCancel } from "./OrderCancel.js";
export const protobufPackage = "protobuf";
function createBaseCancelOrderRequest() {
    return { orderId: undefined, orderCancel: undefined };
}
export const CancelOrderRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.orderId !== undefined) {
            writer.uint32(8).int32(message.orderId);
        }
        if (message.orderCancel !== undefined) {
            OrderCancel.encode(message.orderCancel, writer.uint32(18).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseCancelOrderRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.orderId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.orderCancel = OrderCancel.decode(reader, reader.uint32());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            orderId: isSet(object.orderId) ? globalThis.Number(object.orderId) : undefined,
            orderCancel: isSet(object.orderCancel) ? OrderCancel.fromJSON(object.orderCancel) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.orderId !== undefined) {
            obj.orderId = Math.round(message.orderId);
        }
        if (message.orderCancel !== undefined) {
            obj.orderCancel = OrderCancel.toJSON(message.orderCancel);
        }
        return obj;
    },
    create(base) {
        return CancelOrderRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseCancelOrderRequest();
        message.orderId = object.orderId ?? undefined;
        message.orderCancel = (object.orderCancel !== undefined && object.orderCancel !== null)
            ? OrderCancel.fromPartial(object.orderCancel)
            : undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=CancelOrderRequest.js.map