// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: CompletedOrder.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Contract } from "./Contract.js";
import { Order } from "./Order.js";
import { OrderState } from "./OrderState.js";
export const protobufPackage = "protobuf";
function createBaseCompletedOrder() {
    return { contract: undefined, order: undefined, orderState: undefined };
}
export const CompletedOrder = {
    encode(message, writer = new BinaryWriter()) {
        if (message.contract !== undefined) {
            Contract.encode(message.contract, writer.uint32(10).fork()).join();
        }
        if (message.order !== undefined) {
            Order.encode(message.order, writer.uint32(18).fork()).join();
        }
        if (message.orderState !== undefined) {
            OrderState.encode(message.orderState, writer.uint32(26).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseCompletedOrder();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.contract = Contract.decode(reader, reader.uint32());
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.order = Order.decode(reader, reader.uint32());
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.orderState = OrderState.decode(reader, reader.uint32());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            contract: isSet(object.contract) ? Contract.fromJSON(object.contract) : undefined,
            order: isSet(object.order) ? Order.fromJSON(object.order) : undefined,
            orderState: isSet(object.orderState) ? OrderState.fromJSON(object.orderState) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.contract !== undefined) {
            obj.contract = Contract.toJSON(message.contract);
        }
        if (message.order !== undefined) {
            obj.order = Order.toJSON(message.order);
        }
        if (message.orderState !== undefined) {
            obj.orderState = OrderState.toJSON(message.orderState);
        }
        return obj;
    },
    create(base) {
        return CompletedOrder.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseCompletedOrder();
        message.contract = (object.contract !== undefined && object.contract !== null)
            ? Contract.fromPartial(object.contract)
            : undefined;
        message.order = (object.order !== undefined && object.order !== null) ? Order.fromPartial(object.order) : undefined;
        message.orderState = (object.orderState !== undefined && object.orderState !== null)
            ? OrderState.fromPartial(object.orderState)
            : undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=CompletedOrder.js.map