// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: CompletedOrdersRequest.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseCompletedOrdersRequest() {
    return { apiOnly: undefined };
}
export const CompletedOrdersRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.apiOnly !== undefined) {
            writer.uint32(8).bool(message.apiOnly);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseCompletedOrdersRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.apiOnly = reader.bool();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { apiOnly: isSet(object.apiOnly) ? globalThis.Boolean(object.apiOnly) : undefined };
    },
    toJSON(message) {
        const obj = {};
        if (message.apiOnly !== undefined) {
            obj.apiOnly = message.apiOnly;
        }
        return obj;
    },
    create(base) {
        return CompletedOrdersRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseCompletedOrdersRequest();
        message.apiOnly = object.apiOnly ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=CompletedOrdersRequest.js.map