// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: ContractDescription.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Contract } from "./Contract.js";
export const protobufPackage = "protobuf";
function createBaseContractDescription() {
    return { contract: undefined, derivativeSecTypes: [] };
}
export const ContractDescription = {
    encode(message, writer = new BinaryWriter()) {
        if (message.contract !== undefined) {
            Contract.encode(message.contract, writer.uint32(10).fork()).join();
        }
        for (const v of message.derivativeSecTypes) {
            writer.uint32(18).string(v);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseContractDescription();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.contract = Contract.decode(reader, reader.uint32());
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.derivativeSecTypes.push(reader.string());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            contract: isSet(object.contract) ? Contract.fromJSON(object.contract) : undefined,
            derivativeSecTypes: globalThis.Array.isArray(object?.derivativeSecTypes)
                ? object.derivativeSecTypes.map((e) => globalThis.String(e))
                : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.contract !== undefined) {
            obj.contract = Contract.toJSON(message.contract);
        }
        if (message.derivativeSecTypes?.length) {
            obj.derivativeSecTypes = message.derivativeSecTypes;
        }
        return obj;
    },
    create(base) {
        return ContractDescription.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseContractDescription();
        message.contract = (object.contract !== undefined && object.contract !== null)
            ? Contract.fromPartial(object.contract)
            : undefined;
        message.derivativeSecTypes = object.derivativeSecTypes?.map((e) => e) || [];
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=ContractDescription.js.map