// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: CurrentTimeInMillis.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseCurrentTimeInMillis() {
    return { currentTimeInMillis: undefined };
}
export const CurrentTimeInMillis = {
    encode(message, writer = new BinaryWriter()) {
        if (message.currentTimeInMillis !== undefined) {
            writer.uint32(8).int64(message.currentTimeInMillis);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseCurrentTimeInMillis();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.currentTimeInMillis = longToNumber(reader.int64());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            currentTimeInMillis: isSet(object.currentTimeInMillis)
                ? globalThis.Number(object.currentTimeInMillis)
                : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.currentTimeInMillis !== undefined) {
            obj.currentTimeInMillis = Math.round(message.currentTimeInMillis);
        }
        return obj;
    },
    create(base) {
        return CurrentTimeInMillis.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseCurrentTimeInMillis();
        message.currentTimeInMillis = object.currentTimeInMillis ?? undefined;
        return message;
    },
};
function longToNumber(int64) {
    const num = globalThis.Number(int64.toString());
    if (num > globalThis.Number.MAX_SAFE_INTEGER) {
        throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
    }
    if (num < globalThis.Number.MIN_SAFE_INTEGER) {
        throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
    }
    return num;
}
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=CurrentTimeInMillis.js.map