// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: ExecutionDetails.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Contract } from "./Contract.js";
import { Execution } from "./Execution.js";
export const protobufPackage = "protobuf";
function createBaseExecutionDetails() {
    return { reqId: undefined, contract: undefined, execution: undefined };
}
export const ExecutionDetails = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        if (message.contract !== undefined) {
            Contract.encode(message.contract, writer.uint32(18).fork()).join();
        }
        if (message.execution !== undefined) {
            Execution.encode(message.execution, writer.uint32(26).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseExecutionDetails();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.contract = Contract.decode(reader, reader.uint32());
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.execution = Execution.decode(reader, reader.uint32());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            contract: isSet(object.contract) ? Contract.fromJSON(object.contract) : undefined,
            execution: isSet(object.execution) ? Execution.fromJSON(object.execution) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.contract !== undefined) {
            obj.contract = Contract.toJSON(message.contract);
        }
        if (message.execution !== undefined) {
            obj.execution = Execution.toJSON(message.execution);
        }
        return obj;
    },
    create(base) {
        return ExecutionDetails.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseExecutionDetails();
        message.reqId = object.reqId ?? undefined;
        message.contract = (object.contract !== undefined && object.contract !== null)
            ? Contract.fromPartial(object.contract)
            : undefined;
        message.execution = (object.execution !== undefined && object.execution !== null)
            ? Execution.fromPartial(object.execution)
            : undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=ExecutionDetails.js.map