// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: FamilyCodes.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { FamilyCode } from "./FamilyCode.js";
export const protobufPackage = "protobuf";
function createBaseFamilyCodes() {
    return { familyCodes: [] };
}
export const FamilyCodes = {
    encode(message, writer = new BinaryWriter()) {
        for (const v of message.familyCodes) {
            FamilyCode.encode(v, writer.uint32(10).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseFamilyCodes();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.familyCodes.push(FamilyCode.decode(reader, reader.uint32()));
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            familyCodes: globalThis.Array.isArray(object?.familyCodes)
                ? object.familyCodes.map((e) => FamilyCode.fromJSON(e))
                : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.familyCodes?.length) {
            obj.familyCodes = message.familyCodes.map((e) => FamilyCode.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return FamilyCodes.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseFamilyCodes();
        message.familyCodes = object.familyCodes?.map((e) => FamilyCode.fromPartial(e)) || [];
        return message;
    },
};
//# sourceMappingURL=FamilyCodes.js.map