// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: FamilyCode.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseFamilyCode() {
    return { accountId: undefined, familyCode: undefined };
}
export const FamilyCode = {
    encode(message, writer = new BinaryWriter()) {
        if (message.accountId !== undefined) {
            writer.uint32(10).string(message.accountId);
        }
        if (message.familyCode !== undefined) {
            writer.uint32(18).string(message.familyCode);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseFamilyCode();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.accountId = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.familyCode = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            accountId: isSet(object.accountId) ? globalThis.String(object.accountId) : undefined,
            familyCode: isSet(object.familyCode) ? globalThis.String(object.familyCode) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.accountId !== undefined) {
            obj.accountId = message.accountId;
        }
        if (message.familyCode !== undefined) {
            obj.familyCode = message.familyCode;
        }
        return obj;
    },
    create(base) {
        return FamilyCode.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseFamilyCode();
        message.accountId = object.accountId ?? undefined;
        message.familyCode = object.familyCode ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=FamilyCode.js.map