// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: FAReplace.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseFAReplace() {
    return { reqId: undefined, faDataType: undefined, xml: undefined };
}
export const FAReplace = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        if (message.faDataType !== undefined) {
            writer.uint32(16).int32(message.faDataType);
        }
        if (message.xml !== undefined) {
            writer.uint32(26).string(message.xml);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseFAReplace();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.faDataType = reader.int32();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.xml = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            faDataType: isSet(object.faDataType) ? globalThis.Number(object.faDataType) : undefined,
            xml: isSet(object.xml) ? globalThis.String(object.xml) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.faDataType !== undefined) {
            obj.faDataType = Math.round(message.faDataType);
        }
        if (message.xml !== undefined) {
            obj.xml = message.xml;
        }
        return obj;
    },
    create(base) {
        return FAReplace.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseFAReplace();
        message.reqId = object.reqId ?? undefined;
        message.faDataType = object.faDataType ?? undefined;
        message.xml = object.xml ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=FAReplace.js.map