// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: FARequest.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseFARequest() {
    return { faDataType: undefined };
}
export const FARequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.faDataType !== undefined) {
            writer.uint32(8).int32(message.faDataType);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseFARequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.faDataType = reader.int32();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { faDataType: isSet(object.faDataType) ? globalThis.Number(object.faDataType) : undefined };
    },
    toJSON(message) {
        const obj = {};
        if (message.faDataType !== undefined) {
            obj.faDataType = Math.round(message.faDataType);
        }
        return obj;
    },
    create(base) {
        return FARequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseFARequest();
        message.faDataType = object.faDataType ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=FARequest.js.map