// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: FundamentalsDataRequest.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Contract } from "./Contract.js";
export const protobufPackage = "protobuf";
function createBaseFundamentalsDataRequest() {
    return { reqId: undefined, contract: undefined, reportType: undefined, fundamentalsDataOptions: {} };
}
export const FundamentalsDataRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        if (message.contract !== undefined) {
            Contract.encode(message.contract, writer.uint32(18).fork()).join();
        }
        if (message.reportType !== undefined) {
            writer.uint32(26).string(message.reportType);
        }
        globalThis.Object.entries(message.fundamentalsDataOptions).forEach(([key, value]) => {
            FundamentalsDataRequest_FundamentalsDataOptionsEntry.encode({ key: key, value }, writer.uint32(34).fork())
                .join();
        });
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseFundamentalsDataRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.contract = Contract.decode(reader, reader.uint32());
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.reportType = reader.string();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    const entry4 = FundamentalsDataRequest_FundamentalsDataOptionsEntry.decode(reader, reader.uint32());
                    if (entry4.value !== undefined) {
                        message.fundamentalsDataOptions[entry4.key] = entry4.value;
                    }
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            contract: isSet(object.contract) ? Contract.fromJSON(object.contract) : undefined,
            reportType: isSet(object.reportType) ? globalThis.String(object.reportType) : undefined,
            fundamentalsDataOptions: isObject(object.fundamentalsDataOptions)
                ? globalThis.Object.entries(object.fundamentalsDataOptions).reduce((acc, [key, value]) => {
                    acc[key] = globalThis.String(value);
                    return acc;
                }, {})
                : {},
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.contract !== undefined) {
            obj.contract = Contract.toJSON(message.contract);
        }
        if (message.reportType !== undefined) {
            obj.reportType = message.reportType;
        }
        if (message.fundamentalsDataOptions) {
            const entries = globalThis.Object.entries(message.fundamentalsDataOptions);
            if (entries.length > 0) {
                obj.fundamentalsDataOptions = {};
                entries.forEach(([k, v]) => {
                    obj.fundamentalsDataOptions[k] = v;
                });
            }
        }
        return obj;
    },
    create(base) {
        return FundamentalsDataRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseFundamentalsDataRequest();
        message.reqId = object.reqId ?? undefined;
        message.contract = (object.contract !== undefined && object.contract !== null)
            ? Contract.fromPartial(object.contract)
            : undefined;
        message.reportType = object.reportType ?? undefined;
        message.fundamentalsDataOptions =
            globalThis.Object.entries(object.fundamentalsDataOptions ?? {}).reduce((acc, [key, value]) => {
                if (value !== undefined) {
                    acc[key] = globalThis.String(value);
                }
                return acc;
            }, {});
        return message;
    },
};
function createBaseFundamentalsDataRequest_FundamentalsDataOptionsEntry() {
    return { key: "", value: "" };
}
export const FundamentalsDataRequest_FundamentalsDataOptionsEntry = {
    encode(message, writer = new BinaryWriter()) {
        if (message.key !== "") {
            writer.uint32(10).string(message.key);
        }
        if (message.value !== "") {
            writer.uint32(18).string(message.value);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseFundamentalsDataRequest_FundamentalsDataOptionsEntry();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.key = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.value = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            key: isSet(object.key) ? globalThis.String(object.key) : "",
            value: isSet(object.value) ? globalThis.String(object.value) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.key !== "") {
            obj.key = message.key;
        }
        if (message.value !== "") {
            obj.value = message.value;
        }
        return obj;
    },
    create(base) {
        return FundamentalsDataRequest_FundamentalsDataOptionsEntry.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseFundamentalsDataRequest_FundamentalsDataOptionsEntry();
        message.key = object.key ?? "";
        message.value = object.value ?? "";
        return message;
    },
};
function isObject(value) {
    return typeof value === "object" && value !== null;
}
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=FundamentalsDataRequest.js.map