// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: GlobalCancelRequest.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { OrderCancel } from "./OrderCancel.js";
export const protobufPackage = "protobuf";
function createBaseGlobalCancelRequest() {
    return { orderCancel: undefined };
}
export const GlobalCancelRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.orderCancel !== undefined) {
            OrderCancel.encode(message.orderCancel, writer.uint32(10).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseGlobalCancelRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.orderCancel = OrderCancel.decode(reader, reader.uint32());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { orderCancel: isSet(object.orderCancel) ? OrderCancel.fromJSON(object.orderCancel) : undefined };
    },
    toJSON(message) {
        const obj = {};
        if (message.orderCancel !== undefined) {
            obj.orderCancel = OrderCancel.toJSON(message.orderCancel);
        }
        return obj;
    },
    create(base) {
        return GlobalCancelRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseGlobalCancelRequest();
        message.orderCancel = (object.orderCancel !== undefined && object.orderCancel !== null)
            ? OrderCancel.fromPartial(object.orderCancel)
            : undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=GlobalCancelRequest.js.map