// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: HeadTimestampRequest.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Contract } from "./Contract.js";
export const protobufPackage = "protobuf";
function createBaseHeadTimestampRequest() {
    return { reqId: undefined, contract: undefined, useRTH: undefined, whatToShow: undefined, formatDate: undefined };
}
export const HeadTimestampRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        if (message.contract !== undefined) {
            Contract.encode(message.contract, writer.uint32(18).fork()).join();
        }
        if (message.useRTH !== undefined) {
            writer.uint32(24).bool(message.useRTH);
        }
        if (message.whatToShow !== undefined) {
            writer.uint32(34).string(message.whatToShow);
        }
        if (message.formatDate !== undefined) {
            writer.uint32(40).int32(message.formatDate);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseHeadTimestampRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.contract = Contract.decode(reader, reader.uint32());
                    continue;
                }
                case 3: {
                    if (tag !== 24) {
                        break;
                    }
                    message.useRTH = reader.bool();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.whatToShow = reader.string();
                    continue;
                }
                case 5: {
                    if (tag !== 40) {
                        break;
                    }
                    message.formatDate = reader.int32();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            contract: isSet(object.contract) ? Contract.fromJSON(object.contract) : undefined,
            useRTH: isSet(object.useRTH) ? globalThis.Boolean(object.useRTH) : undefined,
            whatToShow: isSet(object.whatToShow) ? globalThis.String(object.whatToShow) : undefined,
            formatDate: isSet(object.formatDate) ? globalThis.Number(object.formatDate) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.contract !== undefined) {
            obj.contract = Contract.toJSON(message.contract);
        }
        if (message.useRTH !== undefined) {
            obj.useRTH = message.useRTH;
        }
        if (message.whatToShow !== undefined) {
            obj.whatToShow = message.whatToShow;
        }
        if (message.formatDate !== undefined) {
            obj.formatDate = Math.round(message.formatDate);
        }
        return obj;
    },
    create(base) {
        return HeadTimestampRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseHeadTimestampRequest();
        message.reqId = object.reqId ?? undefined;
        message.contract = (object.contract !== undefined && object.contract !== null)
            ? Contract.fromPartial(object.contract)
            : undefined;
        message.useRTH = object.useRTH ?? undefined;
        message.whatToShow = object.whatToShow ?? undefined;
        message.formatDate = object.formatDate ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=HeadTimestampRequest.js.map