// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: HistoricalTicksLast.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { HistoricalTickLast } from "./HistoricalTickLast.js";
export const protobufPackage = "protobuf";
function createBaseHistoricalTicksLast() {
    return { reqId: undefined, historicalTicksLast: [], isDone: undefined };
}
export const HistoricalTicksLast = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        for (const v of message.historicalTicksLast) {
            HistoricalTickLast.encode(v, writer.uint32(18).fork()).join();
        }
        if (message.isDone !== undefined) {
            writer.uint32(24).bool(message.isDone);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseHistoricalTicksLast();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.historicalTicksLast.push(HistoricalTickLast.decode(reader, reader.uint32()));
                    continue;
                }
                case 3: {
                    if (tag !== 24) {
                        break;
                    }
                    message.isDone = reader.bool();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            historicalTicksLast: globalThis.Array.isArray(object?.historicalTicksLast)
                ? object.historicalTicksLast.map((e) => HistoricalTickLast.fromJSON(e))
                : [],
            isDone: isSet(object.isDone) ? globalThis.Boolean(object.isDone) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.historicalTicksLast?.length) {
            obj.historicalTicksLast = message.historicalTicksLast.map((e) => HistoricalTickLast.toJSON(e));
        }
        if (message.isDone !== undefined) {
            obj.isDone = message.isDone;
        }
        return obj;
    },
    create(base) {
        return HistoricalTicksLast.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseHistoricalTicksLast();
        message.reqId = object.reqId ?? undefined;
        message.historicalTicksLast = object.historicalTicksLast?.map((e) => HistoricalTickLast.fromPartial(e)) || [];
        message.isDone = object.isDone ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=HistoricalTicksLast.js.map