// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: HistogramDataEntry.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseHistogramDataEntry() {
    return { price: undefined, size: undefined };
}
export const HistogramDataEntry = {
    encode(message, writer = new BinaryWriter()) {
        if (message.price !== undefined) {
            writer.uint32(9).double(message.price);
        }
        if (message.size !== undefined) {
            writer.uint32(18).string(message.size);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseHistogramDataEntry();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 9) {
                        break;
                    }
                    message.price = reader.double();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.size = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            price: isSet(object.price) ? globalThis.Number(object.price) : undefined,
            size: isSet(object.size) ? globalThis.String(object.size) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.price !== undefined) {
            obj.price = message.price;
        }
        if (message.size !== undefined) {
            obj.size = message.size;
        }
        return obj;
    },
    create(base) {
        return HistogramDataEntry.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseHistogramDataEntry();
        message.price = object.price ?? undefined;
        message.size = object.size ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=HistogramDataEntry.js.map