// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: HistoricalTickLast.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { TickAttribLast } from "./TickAttribLast.js";
export const protobufPackage = "protobuf";
function createBaseHistoricalTickLast() {
    return {
        time: undefined,
        tickAttribLast: undefined,
        price: undefined,
        size: undefined,
        exchange: undefined,
        specialConditions: undefined,
    };
}
export const HistoricalTickLast = {
    encode(message, writer = new BinaryWriter()) {
        if (message.time !== undefined) {
            writer.uint32(8).int64(message.time);
        }
        if (message.tickAttribLast !== undefined) {
            TickAttribLast.encode(message.tickAttribLast, writer.uint32(18).fork()).join();
        }
        if (message.price !== undefined) {
            writer.uint32(25).double(message.price);
        }
        if (message.size !== undefined) {
            writer.uint32(34).string(message.size);
        }
        if (message.exchange !== undefined) {
            writer.uint32(42).string(message.exchange);
        }
        if (message.specialConditions !== undefined) {
            writer.uint32(50).string(message.specialConditions);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseHistoricalTickLast();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.time = longToNumber(reader.int64());
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.tickAttribLast = TickAttribLast.decode(reader, reader.uint32());
                    continue;
                }
                case 3: {
                    if (tag !== 25) {
                        break;
                    }
                    message.price = reader.double();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.size = reader.string();
                    continue;
                }
                case 5: {
                    if (tag !== 42) {
                        break;
                    }
                    message.exchange = reader.string();
                    continue;
                }
                case 6: {
                    if (tag !== 50) {
                        break;
                    }
                    message.specialConditions = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            time: isSet(object.time) ? globalThis.Number(object.time) : undefined,
            tickAttribLast: isSet(object.tickAttribLast) ? TickAttribLast.fromJSON(object.tickAttribLast) : undefined,
            price: isSet(object.price) ? globalThis.Number(object.price) : undefined,
            size: isSet(object.size) ? globalThis.String(object.size) : undefined,
            exchange: isSet(object.exchange) ? globalThis.String(object.exchange) : undefined,
            specialConditions: isSet(object.specialConditions) ? globalThis.String(object.specialConditions) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.time !== undefined) {
            obj.time = Math.round(message.time);
        }
        if (message.tickAttribLast !== undefined) {
            obj.tickAttribLast = TickAttribLast.toJSON(message.tickAttribLast);
        }
        if (message.price !== undefined) {
            obj.price = message.price;
        }
        if (message.size !== undefined) {
            obj.size = message.size;
        }
        if (message.exchange !== undefined) {
            obj.exchange = message.exchange;
        }
        if (message.specialConditions !== undefined) {
            obj.specialConditions = message.specialConditions;
        }
        return obj;
    },
    create(base) {
        return HistoricalTickLast.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseHistoricalTickLast();
        message.time = object.time ?? undefined;
        message.tickAttribLast = (object.tickAttribLast !== undefined && object.tickAttribLast !== null)
            ? TickAttribLast.fromPartial(object.tickAttribLast)
            : undefined;
        message.price = object.price ?? undefined;
        message.size = object.size ?? undefined;
        message.exchange = object.exchange ?? undefined;
        message.specialConditions = object.specialConditions ?? undefined;
        return message;
    },
};
function longToNumber(int64) {
    const num = globalThis.Number(int64.toString());
    if (num > globalThis.Number.MAX_SAFE_INTEGER) {
        throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
    }
    if (num < globalThis.Number.MIN_SAFE_INTEGER) {
        throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
    }
    return num;
}
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=HistoricalTickLast.js.map