// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: HistoricalSession.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseHistoricalSession() {
    return { startDateTime: undefined, endDateTime: undefined, refDate: undefined };
}
export const HistoricalSession = {
    encode(message, writer = new BinaryWriter()) {
        if (message.startDateTime !== undefined) {
            writer.uint32(10).string(message.startDateTime);
        }
        if (message.endDateTime !== undefined) {
            writer.uint32(18).string(message.endDateTime);
        }
        if (message.refDate !== undefined) {
            writer.uint32(26).string(message.refDate);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseHistoricalSession();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.startDateTime = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.endDateTime = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.refDate = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            startDateTime: isSet(object.startDateTime) ? globalThis.String(object.startDateTime) : undefined,
            endDateTime: isSet(object.endDateTime) ? globalThis.String(object.endDateTime) : undefined,
            refDate: isSet(object.refDate) ? globalThis.String(object.refDate) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.startDateTime !== undefined) {
            obj.startDateTime = message.startDateTime;
        }
        if (message.endDateTime !== undefined) {
            obj.endDateTime = message.endDateTime;
        }
        if (message.refDate !== undefined) {
            obj.refDate = message.refDate;
        }
        return obj;
    },
    create(base) {
        return HistoricalSession.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseHistoricalSession();
        message.startDateTime = object.startDateTime ?? undefined;
        message.endDateTime = object.endDateTime ?? undefined;
        message.refDate = object.refDate ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=HistoricalSession.js.map