// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: HistoricalDataRequest.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Contract } from "./Contract.js";
export const protobufPackage = "protobuf";
function createBaseHistoricalDataRequest() {
    return {
        reqId: undefined,
        contract: undefined,
        endDateTime: undefined,
        barSizeSetting: undefined,
        duration: undefined,
        useRTH: undefined,
        whatToShow: undefined,
        formatDate: undefined,
        keepUpToDate: undefined,
        chartOptions: {},
    };
}
export const HistoricalDataRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        if (message.contract !== undefined) {
            Contract.encode(message.contract, writer.uint32(18).fork()).join();
        }
        if (message.endDateTime !== undefined) {
            writer.uint32(26).string(message.endDateTime);
        }
        if (message.barSizeSetting !== undefined) {
            writer.uint32(34).string(message.barSizeSetting);
        }
        if (message.duration !== undefined) {
            writer.uint32(42).string(message.duration);
        }
        if (message.useRTH !== undefined) {
            writer.uint32(48).bool(message.useRTH);
        }
        if (message.whatToShow !== undefined) {
            writer.uint32(58).string(message.whatToShow);
        }
        if (message.formatDate !== undefined) {
            writer.uint32(64).int32(message.formatDate);
        }
        if (message.keepUpToDate !== undefined) {
            writer.uint32(72).bool(message.keepUpToDate);
        }
        globalThis.Object.entries(message.chartOptions).forEach(([key, value]) => {
            HistoricalDataRequest_ChartOptionsEntry.encode({ key: key, value }, writer.uint32(82).fork()).join();
        });
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseHistoricalDataRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.contract = Contract.decode(reader, reader.uint32());
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.endDateTime = reader.string();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.barSizeSetting = reader.string();
                    continue;
                }
                case 5: {
                    if (tag !== 42) {
                        break;
                    }
                    message.duration = reader.string();
                    continue;
                }
                case 6: {
                    if (tag !== 48) {
                        break;
                    }
                    message.useRTH = reader.bool();
                    continue;
                }
                case 7: {
                    if (tag !== 58) {
                        break;
                    }
                    message.whatToShow = reader.string();
                    continue;
                }
                case 8: {
                    if (tag !== 64) {
                        break;
                    }
                    message.formatDate = reader.int32();
                    continue;
                }
                case 9: {
                    if (tag !== 72) {
                        break;
                    }
                    message.keepUpToDate = reader.bool();
                    continue;
                }
                case 10: {
                    if (tag !== 82) {
                        break;
                    }
                    const entry10 = HistoricalDataRequest_ChartOptionsEntry.decode(reader, reader.uint32());
                    if (entry10.value !== undefined) {
                        message.chartOptions[entry10.key] = entry10.value;
                    }
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            contract: isSet(object.contract) ? Contract.fromJSON(object.contract) : undefined,
            endDateTime: isSet(object.endDateTime) ? globalThis.String(object.endDateTime) : undefined,
            barSizeSetting: isSet(object.barSizeSetting) ? globalThis.String(object.barSizeSetting) : undefined,
            duration: isSet(object.duration) ? globalThis.String(object.duration) : undefined,
            useRTH: isSet(object.useRTH) ? globalThis.Boolean(object.useRTH) : undefined,
            whatToShow: isSet(object.whatToShow) ? globalThis.String(object.whatToShow) : undefined,
            formatDate: isSet(object.formatDate) ? globalThis.Number(object.formatDate) : undefined,
            keepUpToDate: isSet(object.keepUpToDate) ? globalThis.Boolean(object.keepUpToDate) : undefined,
            chartOptions: isObject(object.chartOptions)
                ? globalThis.Object.entries(object.chartOptions).reduce((acc, [key, value]) => {
                    acc[key] = globalThis.String(value);
                    return acc;
                }, {})
                : {},
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.contract !== undefined) {
            obj.contract = Contract.toJSON(message.contract);
        }
        if (message.endDateTime !== undefined) {
            obj.endDateTime = message.endDateTime;
        }
        if (message.barSizeSetting !== undefined) {
            obj.barSizeSetting = message.barSizeSetting;
        }
        if (message.duration !== undefined) {
            obj.duration = message.duration;
        }
        if (message.useRTH !== undefined) {
            obj.useRTH = message.useRTH;
        }
        if (message.whatToShow !== undefined) {
            obj.whatToShow = message.whatToShow;
        }
        if (message.formatDate !== undefined) {
            obj.formatDate = Math.round(message.formatDate);
        }
        if (message.keepUpToDate !== undefined) {
            obj.keepUpToDate = message.keepUpToDate;
        }
        if (message.chartOptions) {
            const entries = globalThis.Object.entries(message.chartOptions);
            if (entries.length > 0) {
                obj.chartOptions = {};
                entries.forEach(([k, v]) => {
                    obj.chartOptions[k] = v;
                });
            }
        }
        return obj;
    },
    create(base) {
        return HistoricalDataRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseHistoricalDataRequest();
        message.reqId = object.reqId ?? undefined;
        message.contract = (object.contract !== undefined && object.contract !== null)
            ? Contract.fromPartial(object.contract)
            : undefined;
        message.endDateTime = object.endDateTime ?? undefined;
        message.barSizeSetting = object.barSizeSetting ?? undefined;
        message.duration = object.duration ?? undefined;
        message.useRTH = object.useRTH ?? undefined;
        message.whatToShow = object.whatToShow ?? undefined;
        message.formatDate = object.formatDate ?? undefined;
        message.keepUpToDate = object.keepUpToDate ?? undefined;
        message.chartOptions = globalThis.Object.entries(object.chartOptions ?? {}).reduce((acc, [key, value]) => {
            if (value !== undefined) {
                acc[key] = globalThis.String(value);
            }
            return acc;
        }, {});
        return message;
    },
};
function createBaseHistoricalDataRequest_ChartOptionsEntry() {
    return { key: "", value: "" };
}
export const HistoricalDataRequest_ChartOptionsEntry = {
    encode(message, writer = new BinaryWriter()) {
        if (message.key !== "") {
            writer.uint32(10).string(message.key);
        }
        if (message.value !== "") {
            writer.uint32(18).string(message.value);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseHistoricalDataRequest_ChartOptionsEntry();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.key = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.value = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            key: isSet(object.key) ? globalThis.String(object.key) : "",
            value: isSet(object.value) ? globalThis.String(object.value) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.key !== "") {
            obj.key = message.key;
        }
        if (message.value !== "") {
            obj.value = message.value;
        }
        return obj;
    },
    create(base) {
        return HistoricalDataRequest_ChartOptionsEntry.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseHistoricalDataRequest_ChartOptionsEntry();
        message.key = object.key ?? "";
        message.value = object.value ?? "";
        return message;
    },
};
function isObject(value) {
    return typeof value === "object" && value !== null;
}
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=HistoricalDataRequest.js.map