// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: HistoricalTick.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseHistoricalTick() {
    return { time: undefined, price: undefined, size: undefined };
}
export const HistoricalTick = {
    encode(message, writer = new BinaryWriter()) {
        if (message.time !== undefined) {
            writer.uint32(8).int64(message.time);
        }
        if (message.price !== undefined) {
            writer.uint32(17).double(message.price);
        }
        if (message.size !== undefined) {
            writer.uint32(26).string(message.size);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseHistoricalTick();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.time = longToNumber(reader.int64());
                    continue;
                }
                case 2: {
                    if (tag !== 17) {
                        break;
                    }
                    message.price = reader.double();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.size = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            time: isSet(object.time) ? globalThis.Number(object.time) : undefined,
            price: isSet(object.price) ? globalThis.Number(object.price) : undefined,
            size: isSet(object.size) ? globalThis.String(object.size) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.time !== undefined) {
            obj.time = Math.round(message.time);
        }
        if (message.price !== undefined) {
            obj.price = message.price;
        }
        if (message.size !== undefined) {
            obj.size = message.size;
        }
        return obj;
    },
    create(base) {
        return HistoricalTick.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseHistoricalTick();
        message.time = object.time ?? undefined;
        message.price = object.price ?? undefined;
        message.size = object.size ?? undefined;
        return message;
    },
};
function longToNumber(int64) {
    const num = globalThis.Number(int64.toString());
    if (num > globalThis.Number.MAX_SAFE_INTEGER) {
        throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
    }
    if (num < globalThis.Number.MIN_SAFE_INTEGER) {
        throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
    }
    return num;
}
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=HistoricalTick.js.map