// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: HistoricalDataEnd.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseHistoricalDataEnd() {
    return { reqId: undefined, startDateStr: undefined, endDateStr: undefined };
}
export const HistoricalDataEnd = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        if (message.startDateStr !== undefined) {
            writer.uint32(18).string(message.startDateStr);
        }
        if (message.endDateStr !== undefined) {
            writer.uint32(26).string(message.endDateStr);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseHistoricalDataEnd();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.startDateStr = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.endDateStr = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            startDateStr: isSet(object.startDateStr) ? globalThis.String(object.startDateStr) : undefined,
            endDateStr: isSet(object.endDateStr) ? globalThis.String(object.endDateStr) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.startDateStr !== undefined) {
            obj.startDateStr = message.startDateStr;
        }
        if (message.endDateStr !== undefined) {
            obj.endDateStr = message.endDateStr;
        }
        return obj;
    },
    create(base) {
        return HistoricalDataEnd.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseHistoricalDataEnd();
        message.reqId = object.reqId ?? undefined;
        message.startDateStr = object.startDateStr ?? undefined;
        message.endDateStr = object.endDateStr ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=HistoricalDataEnd.js.map