// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: HistoricalDataUpdate.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { HistoricalDataBar } from "./HistoricalDataBar.js";
export const protobufPackage = "protobuf";
function createBaseHistoricalDataUpdate() {
    return { reqId: undefined, historicalDataBar: undefined };
}
export const HistoricalDataUpdate = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        if (message.historicalDataBar !== undefined) {
            HistoricalDataBar.encode(message.historicalDataBar, writer.uint32(18).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseHistoricalDataUpdate();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.historicalDataBar = HistoricalDataBar.decode(reader, reader.uint32());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            historicalDataBar: isSet(object.historicalDataBar)
                ? HistoricalDataBar.fromJSON(object.historicalDataBar)
                : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.historicalDataBar !== undefined) {
            obj.historicalDataBar = HistoricalDataBar.toJSON(message.historicalDataBar);
        }
        return obj;
    },
    create(base) {
        return HistoricalDataUpdate.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseHistoricalDataUpdate();
        message.reqId = object.reqId ?? undefined;
        message.historicalDataBar = (object.historicalDataBar !== undefined && object.historicalDataBar !== null)
            ? HistoricalDataBar.fromPartial(object.historicalDataBar)
            : undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=HistoricalDataUpdate.js.map