// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: HistoricalData.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { HistoricalDataBar } from "./HistoricalDataBar.js";
export const protobufPackage = "protobuf";
function createBaseHistoricalData() {
    return { reqId: undefined, historicalDataBars: [] };
}
export const HistoricalData = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        for (const v of message.historicalDataBars) {
            HistoricalDataBar.encode(v, writer.uint32(18).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseHistoricalData();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.historicalDataBars.push(HistoricalDataBar.decode(reader, reader.uint32()));
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            historicalDataBars: globalThis.Array.isArray(object?.historicalDataBars)
                ? object.historicalDataBars.map((e) => HistoricalDataBar.fromJSON(e))
                : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.historicalDataBars?.length) {
            obj.historicalDataBars = message.historicalDataBars.map((e) => HistoricalDataBar.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return HistoricalData.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseHistoricalData();
        message.reqId = object.reqId ?? undefined;
        message.historicalDataBars = object.historicalDataBars?.map((e) => HistoricalDataBar.fromPartial(e)) || [];
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=HistoricalData.js.map