// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: HistoricalTickBidAsk.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { TickAttribBidAsk } from "./TickAttribBidAsk.js";
export const protobufPackage = "protobuf";
function createBaseHistoricalTickBidAsk() {
    return {
        time: undefined,
        tickAttribBidAsk: undefined,
        priceBid: undefined,
        priceAsk: undefined,
        sizeBid: undefined,
        sizeAsk: undefined,
    };
}
export const HistoricalTickBidAsk = {
    encode(message, writer = new BinaryWriter()) {
        if (message.time !== undefined) {
            writer.uint32(8).int64(message.time);
        }
        if (message.tickAttribBidAsk !== undefined) {
            TickAttribBidAsk.encode(message.tickAttribBidAsk, writer.uint32(18).fork()).join();
        }
        if (message.priceBid !== undefined) {
            writer.uint32(25).double(message.priceBid);
        }
        if (message.priceAsk !== undefined) {
            writer.uint32(33).double(message.priceAsk);
        }
        if (message.sizeBid !== undefined) {
            writer.uint32(42).string(message.sizeBid);
        }
        if (message.sizeAsk !== undefined) {
            writer.uint32(50).string(message.sizeAsk);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseHistoricalTickBidAsk();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.time = longToNumber(reader.int64());
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.tickAttribBidAsk = TickAttribBidAsk.decode(reader, reader.uint32());
                    continue;
                }
                case 3: {
                    if (tag !== 25) {
                        break;
                    }
                    message.priceBid = reader.double();
                    continue;
                }
                case 4: {
                    if (tag !== 33) {
                        break;
                    }
                    message.priceAsk = reader.double();
                    continue;
                }
                case 5: {
                    if (tag !== 42) {
                        break;
                    }
                    message.sizeBid = reader.string();
                    continue;
                }
                case 6: {
                    if (tag !== 50) {
                        break;
                    }
                    message.sizeAsk = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            time: isSet(object.time) ? globalThis.Number(object.time) : undefined,
            tickAttribBidAsk: isSet(object.tickAttribBidAsk) ? TickAttribBidAsk.fromJSON(object.tickAttribBidAsk) : undefined,
            priceBid: isSet(object.priceBid) ? globalThis.Number(object.priceBid) : undefined,
            priceAsk: isSet(object.priceAsk) ? globalThis.Number(object.priceAsk) : undefined,
            sizeBid: isSet(object.sizeBid) ? globalThis.String(object.sizeBid) : undefined,
            sizeAsk: isSet(object.sizeAsk) ? globalThis.String(object.sizeAsk) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.time !== undefined) {
            obj.time = Math.round(message.time);
        }
        if (message.tickAttribBidAsk !== undefined) {
            obj.tickAttribBidAsk = TickAttribBidAsk.toJSON(message.tickAttribBidAsk);
        }
        if (message.priceBid !== undefined) {
            obj.priceBid = message.priceBid;
        }
        if (message.priceAsk !== undefined) {
            obj.priceAsk = message.priceAsk;
        }
        if (message.sizeBid !== undefined) {
            obj.sizeBid = message.sizeBid;
        }
        if (message.sizeAsk !== undefined) {
            obj.sizeAsk = message.sizeAsk;
        }
        return obj;
    },
    create(base) {
        return HistoricalTickBidAsk.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseHistoricalTickBidAsk();
        message.time = object.time ?? undefined;
        message.tickAttribBidAsk = (object.tickAttribBidAsk !== undefined && object.tickAttribBidAsk !== null)
            ? TickAttribBidAsk.fromPartial(object.tickAttribBidAsk)
            : undefined;
        message.priceBid = object.priceBid ?? undefined;
        message.priceAsk = object.priceAsk ?? undefined;
        message.sizeBid = object.sizeBid ?? undefined;
        message.sizeAsk = object.sizeAsk ?? undefined;
        return message;
    },
};
function longToNumber(int64) {
    const num = globalThis.Number(int64.toString());
    if (num > globalThis.Number.MAX_SAFE_INTEGER) {
        throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
    }
    if (num < globalThis.Number.MIN_SAFE_INTEGER) {
        throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
    }
    return num;
}
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=HistoricalTickBidAsk.js.map