// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: HistoricalNews.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseHistoricalNews() {
    return { reqId: undefined, time: undefined, providerCode: undefined, articleId: undefined, headline: undefined };
}
export const HistoricalNews = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        if (message.time !== undefined) {
            writer.uint32(18).string(message.time);
        }
        if (message.providerCode !== undefined) {
            writer.uint32(26).string(message.providerCode);
        }
        if (message.articleId !== undefined) {
            writer.uint32(34).string(message.articleId);
        }
        if (message.headline !== undefined) {
            writer.uint32(42).string(message.headline);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseHistoricalNews();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.time = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.providerCode = reader.string();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.articleId = reader.string();
                    continue;
                }
                case 5: {
                    if (tag !== 42) {
                        break;
                    }
                    message.headline = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            time: isSet(object.time) ? globalThis.String(object.time) : undefined,
            providerCode: isSet(object.providerCode) ? globalThis.String(object.providerCode) : undefined,
            articleId: isSet(object.articleId) ? globalThis.String(object.articleId) : undefined,
            headline: isSet(object.headline) ? globalThis.String(object.headline) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.time !== undefined) {
            obj.time = message.time;
        }
        if (message.providerCode !== undefined) {
            obj.providerCode = message.providerCode;
        }
        if (message.articleId !== undefined) {
            obj.articleId = message.articleId;
        }
        if (message.headline !== undefined) {
            obj.headline = message.headline;
        }
        return obj;
    },
    create(base) {
        return HistoricalNews.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseHistoricalNews();
        message.reqId = object.reqId ?? undefined;
        message.time = object.time ?? undefined;
        message.providerCode = object.providerCode ?? undefined;
        message.articleId = object.articleId ?? undefined;
        message.headline = object.headline ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=HistoricalNews.js.map