// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: HistoricalTicks.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { HistoricalTick } from "./HistoricalTick.js";
export const protobufPackage = "protobuf";
function createBaseHistoricalTicks() {
    return { reqId: undefined, historicalTicks: [], isDone: undefined };
}
export const HistoricalTicks = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        for (const v of message.historicalTicks) {
            HistoricalTick.encode(v, writer.uint32(18).fork()).join();
        }
        if (message.isDone !== undefined) {
            writer.uint32(24).bool(message.isDone);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseHistoricalTicks();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.historicalTicks.push(HistoricalTick.decode(reader, reader.uint32()));
                    continue;
                }
                case 3: {
                    if (tag !== 24) {
                        break;
                    }
                    message.isDone = reader.bool();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            historicalTicks: globalThis.Array.isArray(object?.historicalTicks)
                ? object.historicalTicks.map((e) => HistoricalTick.fromJSON(e))
                : [],
            isDone: isSet(object.isDone) ? globalThis.Boolean(object.isDone) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.historicalTicks?.length) {
            obj.historicalTicks = message.historicalTicks.map((e) => HistoricalTick.toJSON(e));
        }
        if (message.isDone !== undefined) {
            obj.isDone = message.isDone;
        }
        return obj;
    },
    create(base) {
        return HistoricalTicks.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseHistoricalTicks();
        message.reqId = object.reqId ?? undefined;
        message.historicalTicks = object.historicalTicks?.map((e) => HistoricalTick.fromPartial(e)) || [];
        message.isDone = object.isDone ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=HistoricalTicks.js.map