// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: LockAndExitConfig.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseLockAndExitConfig() {
    return { autoLogoffTime: undefined, autoLogoffPeriod: undefined, autoLogoffType: undefined };
}
export const LockAndExitConfig = {
    encode(message, writer = new BinaryWriter()) {
        if (message.autoLogoffTime !== undefined) {
            writer.uint32(10).string(message.autoLogoffTime);
        }
        if (message.autoLogoffPeriod !== undefined) {
            writer.uint32(18).string(message.autoLogoffPeriod);
        }
        if (message.autoLogoffType !== undefined) {
            writer.uint32(26).string(message.autoLogoffType);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseLockAndExitConfig();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.autoLogoffTime = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.autoLogoffPeriod = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.autoLogoffType = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            autoLogoffTime: isSet(object.autoLogoffTime) ? globalThis.String(object.autoLogoffTime) : undefined,
            autoLogoffPeriod: isSet(object.autoLogoffPeriod) ? globalThis.String(object.autoLogoffPeriod) : undefined,
            autoLogoffType: isSet(object.autoLogoffType) ? globalThis.String(object.autoLogoffType) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.autoLogoffTime !== undefined) {
            obj.autoLogoffTime = message.autoLogoffTime;
        }
        if (message.autoLogoffPeriod !== undefined) {
            obj.autoLogoffPeriod = message.autoLogoffPeriod;
        }
        if (message.autoLogoffType !== undefined) {
            obj.autoLogoffType = message.autoLogoffType;
        }
        return obj;
    },
    create(base) {
        return LockAndExitConfig.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseLockAndExitConfig();
        message.autoLogoffTime = object.autoLogoffTime ?? undefined;
        message.autoLogoffPeriod = object.autoLogoffPeriod ?? undefined;
        message.autoLogoffType = object.autoLogoffType ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=LockAndExitConfig.js.map