// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: ManagedAccounts.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseManagedAccounts() {
    return { accountsList: undefined };
}
export const ManagedAccounts = {
    encode(message, writer = new BinaryWriter()) {
        if (message.accountsList !== undefined) {
            writer.uint32(10).string(message.accountsList);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseManagedAccounts();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.accountsList = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { accountsList: isSet(object.accountsList) ? globalThis.String(object.accountsList) : undefined };
    },
    toJSON(message) {
        const obj = {};
        if (message.accountsList !== undefined) {
            obj.accountsList = message.accountsList;
        }
        return obj;
    },
    create(base) {
        return ManagedAccounts.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseManagedAccounts();
        message.accountsList = object.accountsList ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=ManagedAccounts.js.map