// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: MarketDepthExchanges.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { DepthMarketDataDescription } from "./DepthMarketDataDescription.js";
export const protobufPackage = "protobuf";
function createBaseMarketDepthExchanges() {
    return { depthMarketDataDescriptions: [] };
}
export const MarketDepthExchanges = {
    encode(message, writer = new BinaryWriter()) {
        for (const v of message.depthMarketDataDescriptions) {
            DepthMarketDataDescription.encode(v, writer.uint32(10).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseMarketDepthExchanges();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.depthMarketDataDescriptions.push(DepthMarketDataDescription.decode(reader, reader.uint32()));
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            depthMarketDataDescriptions: globalThis.Array.isArray(object?.depthMarketDataDescriptions)
                ? object.depthMarketDataDescriptions.map((e) => DepthMarketDataDescription.fromJSON(e))
                : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.depthMarketDataDescriptions?.length) {
            obj.depthMarketDataDescriptions = message.depthMarketDataDescriptions.map((e) => DepthMarketDataDescription.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return MarketDepthExchanges.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseMarketDepthExchanges();
        message.depthMarketDataDescriptions =
            object.depthMarketDataDescriptions?.map((e) => DepthMarketDataDescription.fromPartial(e)) || [];
        return message;
    },
};
//# sourceMappingURL=MarketDepthExchanges.js.map