// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: MarketDepthRequest.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Contract } from "./Contract.js";
export const protobufPackage = "protobuf";
function createBaseMarketDepthRequest() {
    return { reqId: undefined, contract: undefined, numRows: undefined, isSmartDepth: undefined, marketDepthOptions: {} };
}
export const MarketDepthRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        if (message.contract !== undefined) {
            Contract.encode(message.contract, writer.uint32(18).fork()).join();
        }
        if (message.numRows !== undefined) {
            writer.uint32(24).int32(message.numRows);
        }
        if (message.isSmartDepth !== undefined) {
            writer.uint32(32).bool(message.isSmartDepth);
        }
        globalThis.Object.entries(message.marketDepthOptions).forEach(([key, value]) => {
            MarketDepthRequest_MarketDepthOptionsEntry.encode({ key: key, value }, writer.uint32(42).fork()).join();
        });
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseMarketDepthRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.contract = Contract.decode(reader, reader.uint32());
                    continue;
                }
                case 3: {
                    if (tag !== 24) {
                        break;
                    }
                    message.numRows = reader.int32();
                    continue;
                }
                case 4: {
                    if (tag !== 32) {
                        break;
                    }
                    message.isSmartDepth = reader.bool();
                    continue;
                }
                case 5: {
                    if (tag !== 42) {
                        break;
                    }
                    const entry5 = MarketDepthRequest_MarketDepthOptionsEntry.decode(reader, reader.uint32());
                    if (entry5.value !== undefined) {
                        message.marketDepthOptions[entry5.key] = entry5.value;
                    }
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            contract: isSet(object.contract) ? Contract.fromJSON(object.contract) : undefined,
            numRows: isSet(object.numRows) ? globalThis.Number(object.numRows) : undefined,
            isSmartDepth: isSet(object.isSmartDepth) ? globalThis.Boolean(object.isSmartDepth) : undefined,
            marketDepthOptions: isObject(object.marketDepthOptions)
                ? globalThis.Object.entries(object.marketDepthOptions).reduce((acc, [key, value]) => {
                    acc[key] = globalThis.String(value);
                    return acc;
                }, {})
                : {},
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.contract !== undefined) {
            obj.contract = Contract.toJSON(message.contract);
        }
        if (message.numRows !== undefined) {
            obj.numRows = Math.round(message.numRows);
        }
        if (message.isSmartDepth !== undefined) {
            obj.isSmartDepth = message.isSmartDepth;
        }
        if (message.marketDepthOptions) {
            const entries = globalThis.Object.entries(message.marketDepthOptions);
            if (entries.length > 0) {
                obj.marketDepthOptions = {};
                entries.forEach(([k, v]) => {
                    obj.marketDepthOptions[k] = v;
                });
            }
        }
        return obj;
    },
    create(base) {
        return MarketDepthRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseMarketDepthRequest();
        message.reqId = object.reqId ?? undefined;
        message.contract = (object.contract !== undefined && object.contract !== null)
            ? Contract.fromPartial(object.contract)
            : undefined;
        message.numRows = object.numRows ?? undefined;
        message.isSmartDepth = object.isSmartDepth ?? undefined;
        message.marketDepthOptions = globalThis.Object.entries(object.marketDepthOptions ?? {})
            .reduce((acc, [key, value]) => {
            if (value !== undefined) {
                acc[key] = globalThis.String(value);
            }
            return acc;
        }, {});
        return message;
    },
};
function createBaseMarketDepthRequest_MarketDepthOptionsEntry() {
    return { key: "", value: "" };
}
export const MarketDepthRequest_MarketDepthOptionsEntry = {
    encode(message, writer = new BinaryWriter()) {
        if (message.key !== "") {
            writer.uint32(10).string(message.key);
        }
        if (message.value !== "") {
            writer.uint32(18).string(message.value);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseMarketDepthRequest_MarketDepthOptionsEntry();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.key = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.value = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            key: isSet(object.key) ? globalThis.String(object.key) : "",
            value: isSet(object.value) ? globalThis.String(object.value) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.key !== "") {
            obj.key = message.key;
        }
        if (message.value !== "") {
            obj.value = message.value;
        }
        return obj;
    },
    create(base) {
        return MarketDepthRequest_MarketDepthOptionsEntry.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseMarketDepthRequest_MarketDepthOptionsEntry();
        message.key = object.key ?? "";
        message.value = object.value ?? "";
        return message;
    },
};
function isObject(value) {
    return typeof value === "object" && value !== null;
}
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=MarketDepthRequest.js.map