// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: NewsArticleRequest.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseNewsArticleRequest() {
    return { reqId: undefined, providerCode: undefined, articleId: undefined, newsArticleOptions: {} };
}
export const NewsArticleRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        if (message.providerCode !== undefined) {
            writer.uint32(18).string(message.providerCode);
        }
        if (message.articleId !== undefined) {
            writer.uint32(26).string(message.articleId);
        }
        globalThis.Object.entries(message.newsArticleOptions).forEach(([key, value]) => {
            NewsArticleRequest_NewsArticleOptionsEntry.encode({ key: key, value }, writer.uint32(34).fork()).join();
        });
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseNewsArticleRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.providerCode = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.articleId = reader.string();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    const entry4 = NewsArticleRequest_NewsArticleOptionsEntry.decode(reader, reader.uint32());
                    if (entry4.value !== undefined) {
                        message.newsArticleOptions[entry4.key] = entry4.value;
                    }
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            providerCode: isSet(object.providerCode) ? globalThis.String(object.providerCode) : undefined,
            articleId: isSet(object.articleId) ? globalThis.String(object.articleId) : undefined,
            newsArticleOptions: isObject(object.newsArticleOptions)
                ? globalThis.Object.entries(object.newsArticleOptions).reduce((acc, [key, value]) => {
                    acc[key] = globalThis.String(value);
                    return acc;
                }, {})
                : {},
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.providerCode !== undefined) {
            obj.providerCode = message.providerCode;
        }
        if (message.articleId !== undefined) {
            obj.articleId = message.articleId;
        }
        if (message.newsArticleOptions) {
            const entries = globalThis.Object.entries(message.newsArticleOptions);
            if (entries.length > 0) {
                obj.newsArticleOptions = {};
                entries.forEach(([k, v]) => {
                    obj.newsArticleOptions[k] = v;
                });
            }
        }
        return obj;
    },
    create(base) {
        return NewsArticleRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseNewsArticleRequest();
        message.reqId = object.reqId ?? undefined;
        message.providerCode = object.providerCode ?? undefined;
        message.articleId = object.articleId ?? undefined;
        message.newsArticleOptions = globalThis.Object.entries(object.newsArticleOptions ?? {})
            .reduce((acc, [key, value]) => {
            if (value !== undefined) {
                acc[key] = globalThis.String(value);
            }
            return acc;
        }, {});
        return message;
    },
};
function createBaseNewsArticleRequest_NewsArticleOptionsEntry() {
    return { key: "", value: "" };
}
export const NewsArticleRequest_NewsArticleOptionsEntry = {
    encode(message, writer = new BinaryWriter()) {
        if (message.key !== "") {
            writer.uint32(10).string(message.key);
        }
        if (message.value !== "") {
            writer.uint32(18).string(message.value);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseNewsArticleRequest_NewsArticleOptionsEntry();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.key = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.value = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            key: isSet(object.key) ? globalThis.String(object.key) : "",
            value: isSet(object.value) ? globalThis.String(object.value) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.key !== "") {
            obj.key = message.key;
        }
        if (message.value !== "") {
            obj.value = message.value;
        }
        return obj;
    },
    create(base) {
        return NewsArticleRequest_NewsArticleOptionsEntry.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseNewsArticleRequest_NewsArticleOptionsEntry();
        message.key = object.key ?? "";
        message.value = object.value ?? "";
        return message;
    },
};
function isObject(value) {
    return typeof value === "object" && value !== null;
}
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=NewsArticleRequest.js.map