// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: NewsProvider.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseNewsProvider() {
    return { providerCode: undefined, providerName: undefined };
}
export const NewsProvider = {
    encode(message, writer = new BinaryWriter()) {
        if (message.providerCode !== undefined) {
            writer.uint32(10).string(message.providerCode);
        }
        if (message.providerName !== undefined) {
            writer.uint32(18).string(message.providerName);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseNewsProvider();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.providerCode = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.providerName = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            providerCode: isSet(object.providerCode) ? globalThis.String(object.providerCode) : undefined,
            providerName: isSet(object.providerName) ? globalThis.String(object.providerName) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.providerCode !== undefined) {
            obj.providerCode = message.providerCode;
        }
        if (message.providerName !== undefined) {
            obj.providerName = message.providerName;
        }
        return obj;
    },
    create(base) {
        return NewsProvider.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseNewsProvider();
        message.providerCode = object.providerCode ?? undefined;
        message.providerName = object.providerName ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=NewsProvider.js.map