// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: NewsProviders.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { NewsProvider } from "./NewsProvider.js";
export const protobufPackage = "protobuf";
function createBaseNewsProviders() {
    return { newsProviders: [] };
}
export const NewsProviders = {
    encode(message, writer = new BinaryWriter()) {
        for (const v of message.newsProviders) {
            NewsProvider.encode(v, writer.uint32(10).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseNewsProviders();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.newsProviders.push(NewsProvider.decode(reader, reader.uint32()));
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            newsProviders: globalThis.Array.isArray(object?.newsProviders)
                ? object.newsProviders.map((e) => NewsProvider.fromJSON(e))
                : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.newsProviders?.length) {
            obj.newsProviders = message.newsProviders.map((e) => NewsProvider.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return NewsProviders.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseNewsProviders();
        message.newsProviders = object.newsProviders?.map((e) => NewsProvider.fromPartial(e)) || [];
        return message;
    },
};
//# sourceMappingURL=NewsProviders.js.map