// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: NewsArticle.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseNewsArticle() {
    return { reqId: undefined, articleType: undefined, articleText: undefined };
}
export const NewsArticle = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        if (message.articleType !== undefined) {
            writer.uint32(16).int32(message.articleType);
        }
        if (message.articleText !== undefined) {
            writer.uint32(26).string(message.articleText);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseNewsArticle();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.articleType = reader.int32();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.articleText = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            articleType: isSet(object.articleType) ? globalThis.Number(object.articleType) : undefined,
            articleText: isSet(object.articleText) ? globalThis.String(object.articleText) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.articleType !== undefined) {
            obj.articleType = Math.round(message.articleType);
        }
        if (message.articleText !== undefined) {
            obj.articleText = message.articleText;
        }
        return obj;
    },
    create(base) {
        return NewsArticle.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseNewsArticle();
        message.reqId = object.reqId ?? undefined;
        message.articleType = object.articleType ?? undefined;
        message.articleText = object.articleText ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=NewsArticle.js.map