// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: NewsBulletinsRequest.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseNewsBulletinsRequest() {
    return { allMessages: undefined };
}
export const NewsBulletinsRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.allMessages !== undefined) {
            writer.uint32(8).bool(message.allMessages);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseNewsBulletinsRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.allMessages = reader.bool();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { allMessages: isSet(object.allMessages) ? globalThis.Boolean(object.allMessages) : undefined };
    },
    toJSON(message) {
        const obj = {};
        if (message.allMessages !== undefined) {
            obj.allMessages = message.allMessages;
        }
        return obj;
    },
    create(base) {
        return NewsBulletinsRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseNewsBulletinsRequest();
        message.allMessages = object.allMessages ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=NewsBulletinsRequest.js.map