// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: NextValidId.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseNextValidId() {
    return { orderId: undefined };
}
export const NextValidId = {
    encode(message, writer = new BinaryWriter()) {
        if (message.orderId !== undefined) {
            writer.uint32(8).int32(message.orderId);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseNextValidId();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.orderId = reader.int32();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { orderId: isSet(object.orderId) ? globalThis.Number(object.orderId) : undefined };
    },
    toJSON(message) {
        const obj = {};
        if (message.orderId !== undefined) {
            obj.orderId = Math.round(message.orderId);
        }
        return obj;
    },
    create(base) {
        return NextValidId.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseNextValidId();
        message.orderId = object.orderId ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=NextValidId.js.map