// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: OrdersConfig.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { OrdersSmartRoutingConfig } from "./OrdersSmartRoutingConfig.js";
export const protobufPackage = "protobuf";
function createBaseOrdersConfig() {
    return { smartRouting: undefined };
}
export const OrdersConfig = {
    encode(message, writer = new BinaryWriter()) {
        if (message.smartRouting !== undefined) {
            OrdersSmartRoutingConfig.encode(message.smartRouting, writer.uint32(10).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseOrdersConfig();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.smartRouting = OrdersSmartRoutingConfig.decode(reader, reader.uint32());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            smartRouting: isSet(object.smartRouting) ? OrdersSmartRoutingConfig.fromJSON(object.smartRouting) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.smartRouting !== undefined) {
            obj.smartRouting = OrdersSmartRoutingConfig.toJSON(message.smartRouting);
        }
        return obj;
    },
    create(base) {
        return OrdersConfig.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseOrdersConfig();
        message.smartRouting = (object.smartRouting !== undefined && object.smartRouting !== null)
            ? OrdersSmartRoutingConfig.fromPartial(object.smartRouting)
            : undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=OrdersConfig.js.map