// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: OrderBound.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseOrderBound() {
    return { permId: undefined, clientId: undefined, orderId: undefined };
}
export const OrderBound = {
    encode(message, writer = new BinaryWriter()) {
        if (message.permId !== undefined) {
            writer.uint32(8).int64(message.permId);
        }
        if (message.clientId !== undefined) {
            writer.uint32(16).int32(message.clientId);
        }
        if (message.orderId !== undefined) {
            writer.uint32(24).int32(message.orderId);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseOrderBound();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.permId = longToNumber(reader.int64());
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.clientId = reader.int32();
                    continue;
                }
                case 3: {
                    if (tag !== 24) {
                        break;
                    }
                    message.orderId = reader.int32();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            permId: isSet(object.permId) ? globalThis.Number(object.permId) : undefined,
            clientId: isSet(object.clientId) ? globalThis.Number(object.clientId) : undefined,
            orderId: isSet(object.orderId) ? globalThis.Number(object.orderId) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.permId !== undefined) {
            obj.permId = Math.round(message.permId);
        }
        if (message.clientId !== undefined) {
            obj.clientId = Math.round(message.clientId);
        }
        if (message.orderId !== undefined) {
            obj.orderId = Math.round(message.orderId);
        }
        return obj;
    },
    create(base) {
        return OrderBound.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseOrderBound();
        message.permId = object.permId ?? undefined;
        message.clientId = object.clientId ?? undefined;
        message.orderId = object.orderId ?? undefined;
        return message;
    },
};
function longToNumber(int64) {
    const num = globalThis.Number(int64.toString());
    if (num > globalThis.Number.MAX_SAFE_INTEGER) {
        throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
    }
    if (num < globalThis.Number.MIN_SAFE_INTEGER) {
        throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
    }
    return num;
}
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=OrderBound.js.map