// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: OrderCancel.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseOrderCancel() {
    return { manualOrderCancelTime: undefined, extOperator: undefined, manualOrderIndicator: undefined };
}
export const OrderCancel = {
    encode(message, writer = new BinaryWriter()) {
        if (message.manualOrderCancelTime !== undefined) {
            writer.uint32(10).string(message.manualOrderCancelTime);
        }
        if (message.extOperator !== undefined) {
            writer.uint32(18).string(message.extOperator);
        }
        if (message.manualOrderIndicator !== undefined) {
            writer.uint32(24).int32(message.manualOrderIndicator);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseOrderCancel();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.manualOrderCancelTime = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.extOperator = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 24) {
                        break;
                    }
                    message.manualOrderIndicator = reader.int32();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            manualOrderCancelTime: isSet(object.manualOrderCancelTime)
                ? globalThis.String(object.manualOrderCancelTime)
                : undefined,
            extOperator: isSet(object.extOperator) ? globalThis.String(object.extOperator) : undefined,
            manualOrderIndicator: isSet(object.manualOrderIndicator)
                ? globalThis.Number(object.manualOrderIndicator)
                : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.manualOrderCancelTime !== undefined) {
            obj.manualOrderCancelTime = message.manualOrderCancelTime;
        }
        if (message.extOperator !== undefined) {
            obj.extOperator = message.extOperator;
        }
        if (message.manualOrderIndicator !== undefined) {
            obj.manualOrderIndicator = Math.round(message.manualOrderIndicator);
        }
        return obj;
    },
    create(base) {
        return OrderCancel.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseOrderCancel();
        message.manualOrderCancelTime = object.manualOrderCancelTime ?? undefined;
        message.extOperator = object.extOperator ?? undefined;
        message.manualOrderIndicator = object.manualOrderIndicator ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=OrderCancel.js.map