// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: OrdersSmartRoutingConfig.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseOrdersSmartRoutingConfig() {
    return {
        seekPriceImprovement: undefined,
        preOpenReroute: undefined,
        doNotRouteToDarkPools: undefined,
        defaultAlgorithm: undefined,
    };
}
export const OrdersSmartRoutingConfig = {
    encode(message, writer = new BinaryWriter()) {
        if (message.seekPriceImprovement !== undefined) {
            writer.uint32(8).bool(message.seekPriceImprovement);
        }
        if (message.preOpenReroute !== undefined) {
            writer.uint32(16).bool(message.preOpenReroute);
        }
        if (message.doNotRouteToDarkPools !== undefined) {
            writer.uint32(24).bool(message.doNotRouteToDarkPools);
        }
        if (message.defaultAlgorithm !== undefined) {
            writer.uint32(34).string(message.defaultAlgorithm);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseOrdersSmartRoutingConfig();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.seekPriceImprovement = reader.bool();
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.preOpenReroute = reader.bool();
                    continue;
                }
                case 3: {
                    if (tag !== 24) {
                        break;
                    }
                    message.doNotRouteToDarkPools = reader.bool();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.defaultAlgorithm = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            seekPriceImprovement: isSet(object.seekPriceImprovement)
                ? globalThis.Boolean(object.seekPriceImprovement)
                : undefined,
            preOpenReroute: isSet(object.preOpenReroute) ? globalThis.Boolean(object.preOpenReroute) : undefined,
            doNotRouteToDarkPools: isSet(object.doNotRouteToDarkPools)
                ? globalThis.Boolean(object.doNotRouteToDarkPools)
                : undefined,
            defaultAlgorithm: isSet(object.defaultAlgorithm) ? globalThis.String(object.defaultAlgorithm) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.seekPriceImprovement !== undefined) {
            obj.seekPriceImprovement = message.seekPriceImprovement;
        }
        if (message.preOpenReroute !== undefined) {
            obj.preOpenReroute = message.preOpenReroute;
        }
        if (message.doNotRouteToDarkPools !== undefined) {
            obj.doNotRouteToDarkPools = message.doNotRouteToDarkPools;
        }
        if (message.defaultAlgorithm !== undefined) {
            obj.defaultAlgorithm = message.defaultAlgorithm;
        }
        return obj;
    },
    create(base) {
        return OrdersSmartRoutingConfig.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseOrdersSmartRoutingConfig();
        message.seekPriceImprovement = object.seekPriceImprovement ?? undefined;
        message.preOpenReroute = object.preOpenReroute ?? undefined;
        message.doNotRouteToDarkPools = object.doNotRouteToDarkPools ?? undefined;
        message.defaultAlgorithm = object.defaultAlgorithm ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=OrdersSmartRoutingConfig.js.map