// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: PlaceOrderRequest.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { AttachedOrders } from "./AttachedOrders.js";
import { Contract } from "./Contract.js";
import { Order } from "./Order.js";
export const protobufPackage = "protobuf";
function createBasePlaceOrderRequest() {
    return { orderId: undefined, contract: undefined, order: undefined, attachedOrders: undefined };
}
export const PlaceOrderRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.orderId !== undefined) {
            writer.uint32(8).int32(message.orderId);
        }
        if (message.contract !== undefined) {
            Contract.encode(message.contract, writer.uint32(18).fork()).join();
        }
        if (message.order !== undefined) {
            Order.encode(message.order, writer.uint32(26).fork()).join();
        }
        if (message.attachedOrders !== undefined) {
            AttachedOrders.encode(message.attachedOrders, writer.uint32(34).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBasePlaceOrderRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.orderId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.contract = Contract.decode(reader, reader.uint32());
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.order = Order.decode(reader, reader.uint32());
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.attachedOrders = AttachedOrders.decode(reader, reader.uint32());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            orderId: isSet(object.orderId) ? globalThis.Number(object.orderId) : undefined,
            contract: isSet(object.contract) ? Contract.fromJSON(object.contract) : undefined,
            order: isSet(object.order) ? Order.fromJSON(object.order) : undefined,
            attachedOrders: isSet(object.attachedOrders) ? AttachedOrders.fromJSON(object.attachedOrders) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.orderId !== undefined) {
            obj.orderId = Math.round(message.orderId);
        }
        if (message.contract !== undefined) {
            obj.contract = Contract.toJSON(message.contract);
        }
        if (message.order !== undefined) {
            obj.order = Order.toJSON(message.order);
        }
        if (message.attachedOrders !== undefined) {
            obj.attachedOrders = AttachedOrders.toJSON(message.attachedOrders);
        }
        return obj;
    },
    create(base) {
        return PlaceOrderRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBasePlaceOrderRequest();
        message.orderId = object.orderId ?? undefined;
        message.contract = (object.contract !== undefined && object.contract !== null)
            ? Contract.fromPartial(object.contract)
            : undefined;
        message.order = (object.order !== undefined && object.order !== null) ? Order.fromPartial(object.order) : undefined;
        message.attachedOrders = (object.attachedOrders !== undefined && object.attachedOrders !== null)
            ? AttachedOrders.fromPartial(object.attachedOrders)
            : undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=PlaceOrderRequest.js.map