// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: PnL.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBasePnL() {
    return { reqId: undefined, dailyPnL: undefined, unrealizedPnL: undefined, realizedPnL: undefined };
}
export const PnL = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        if (message.dailyPnL !== undefined) {
            writer.uint32(17).double(message.dailyPnL);
        }
        if (message.unrealizedPnL !== undefined) {
            writer.uint32(25).double(message.unrealizedPnL);
        }
        if (message.realizedPnL !== undefined) {
            writer.uint32(33).double(message.realizedPnL);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBasePnL();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 17) {
                        break;
                    }
                    message.dailyPnL = reader.double();
                    continue;
                }
                case 3: {
                    if (tag !== 25) {
                        break;
                    }
                    message.unrealizedPnL = reader.double();
                    continue;
                }
                case 4: {
                    if (tag !== 33) {
                        break;
                    }
                    message.realizedPnL = reader.double();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            dailyPnL: isSet(object.dailyPnL) ? globalThis.Number(object.dailyPnL) : undefined,
            unrealizedPnL: isSet(object.unrealizedPnL) ? globalThis.Number(object.unrealizedPnL) : undefined,
            realizedPnL: isSet(object.realizedPnL) ? globalThis.Number(object.realizedPnL) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.dailyPnL !== undefined) {
            obj.dailyPnL = message.dailyPnL;
        }
        if (message.unrealizedPnL !== undefined) {
            obj.unrealizedPnL = message.unrealizedPnL;
        }
        if (message.realizedPnL !== undefined) {
            obj.realizedPnL = message.realizedPnL;
        }
        return obj;
    },
    create(base) {
        return PnL.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBasePnL();
        message.reqId = object.reqId ?? undefined;
        message.dailyPnL = object.dailyPnL ?? undefined;
        message.unrealizedPnL = object.unrealizedPnL ?? undefined;
        message.realizedPnL = object.realizedPnL ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=PnL.js.map