// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: PnLSingle.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBasePnLSingle() {
    return {
        reqId: undefined,
        position: undefined,
        dailyPnL: undefined,
        unrealizedPnL: undefined,
        realizedPnL: undefined,
        value: undefined,
    };
}
export const PnLSingle = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        if (message.position !== undefined) {
            writer.uint32(18).string(message.position);
        }
        if (message.dailyPnL !== undefined) {
            writer.uint32(25).double(message.dailyPnL);
        }
        if (message.unrealizedPnL !== undefined) {
            writer.uint32(33).double(message.unrealizedPnL);
        }
        if (message.realizedPnL !== undefined) {
            writer.uint32(41).double(message.realizedPnL);
        }
        if (message.value !== undefined) {
            writer.uint32(49).double(message.value);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBasePnLSingle();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.position = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 25) {
                        break;
                    }
                    message.dailyPnL = reader.double();
                    continue;
                }
                case 4: {
                    if (tag !== 33) {
                        break;
                    }
                    message.unrealizedPnL = reader.double();
                    continue;
                }
                case 5: {
                    if (tag !== 41) {
                        break;
                    }
                    message.realizedPnL = reader.double();
                    continue;
                }
                case 6: {
                    if (tag !== 49) {
                        break;
                    }
                    message.value = reader.double();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            position: isSet(object.position) ? globalThis.String(object.position) : undefined,
            dailyPnL: isSet(object.dailyPnL) ? globalThis.Number(object.dailyPnL) : undefined,
            unrealizedPnL: isSet(object.unrealizedPnL) ? globalThis.Number(object.unrealizedPnL) : undefined,
            realizedPnL: isSet(object.realizedPnL) ? globalThis.Number(object.realizedPnL) : undefined,
            value: isSet(object.value) ? globalThis.Number(object.value) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.position !== undefined) {
            obj.position = message.position;
        }
        if (message.dailyPnL !== undefined) {
            obj.dailyPnL = message.dailyPnL;
        }
        if (message.unrealizedPnL !== undefined) {
            obj.unrealizedPnL = message.unrealizedPnL;
        }
        if (message.realizedPnL !== undefined) {
            obj.realizedPnL = message.realizedPnL;
        }
        if (message.value !== undefined) {
            obj.value = message.value;
        }
        return obj;
    },
    create(base) {
        return PnLSingle.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBasePnLSingle();
        message.reqId = object.reqId ?? undefined;
        message.position = object.position ?? undefined;
        message.dailyPnL = object.dailyPnL ?? undefined;
        message.unrealizedPnL = object.unrealizedPnL ?? undefined;
        message.realizedPnL = object.realizedPnL ?? undefined;
        message.value = object.value ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=PnLSingle.js.map