// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: PnLSingleRequest.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBasePnLSingleRequest() {
    return { reqId: undefined, account: undefined, modelCode: undefined, conId: undefined };
}
export const PnLSingleRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        if (message.account !== undefined) {
            writer.uint32(18).string(message.account);
        }
        if (message.modelCode !== undefined) {
            writer.uint32(26).string(message.modelCode);
        }
        if (message.conId !== undefined) {
            writer.uint32(32).int32(message.conId);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBasePnLSingleRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.account = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.modelCode = reader.string();
                    continue;
                }
                case 4: {
                    if (tag !== 32) {
                        break;
                    }
                    message.conId = reader.int32();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            account: isSet(object.account) ? globalThis.String(object.account) : undefined,
            modelCode: isSet(object.modelCode) ? globalThis.String(object.modelCode) : undefined,
            conId: isSet(object.conId) ? globalThis.Number(object.conId) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.account !== undefined) {
            obj.account = message.account;
        }
        if (message.modelCode !== undefined) {
            obj.modelCode = message.modelCode;
        }
        if (message.conId !== undefined) {
            obj.conId = Math.round(message.conId);
        }
        return obj;
    },
    create(base) {
        return PnLSingleRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBasePnLSingleRequest();
        message.reqId = object.reqId ?? undefined;
        message.account = object.account ?? undefined;
        message.modelCode = object.modelCode ?? undefined;
        message.conId = object.conId ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=PnLSingleRequest.js.map