// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: Position.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Contract } from "./Contract.js";
export const protobufPackage = "protobuf";
function createBasePosition() {
    return { account: undefined, contract: undefined, position: undefined, avgCost: undefined };
}
export const Position = {
    encode(message, writer = new BinaryWriter()) {
        if (message.account !== undefined) {
            writer.uint32(10).string(message.account);
        }
        if (message.contract !== undefined) {
            Contract.encode(message.contract, writer.uint32(18).fork()).join();
        }
        if (message.position !== undefined) {
            writer.uint32(26).string(message.position);
        }
        if (message.avgCost !== undefined) {
            writer.uint32(33).double(message.avgCost);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBasePosition();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.account = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.contract = Contract.decode(reader, reader.uint32());
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.position = reader.string();
                    continue;
                }
                case 4: {
                    if (tag !== 33) {
                        break;
                    }
                    message.avgCost = reader.double();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            account: isSet(object.account) ? globalThis.String(object.account) : undefined,
            contract: isSet(object.contract) ? Contract.fromJSON(object.contract) : undefined,
            position: isSet(object.position) ? globalThis.String(object.position) : undefined,
            avgCost: isSet(object.avgCost) ? globalThis.Number(object.avgCost) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.account !== undefined) {
            obj.account = message.account;
        }
        if (message.contract !== undefined) {
            obj.contract = Contract.toJSON(message.contract);
        }
        if (message.position !== undefined) {
            obj.position = message.position;
        }
        if (message.avgCost !== undefined) {
            obj.avgCost = message.avgCost;
        }
        return obj;
    },
    create(base) {
        return Position.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBasePosition();
        message.account = object.account ?? undefined;
        message.contract = (object.contract !== undefined && object.contract !== null)
            ? Contract.fromPartial(object.contract)
            : undefined;
        message.position = object.position ?? undefined;
        message.avgCost = object.avgCost ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=Position.js.map