// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: PriceIncrement.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBasePriceIncrement() {
    return { lowEdge: undefined, increment: undefined };
}
export const PriceIncrement = {
    encode(message, writer = new BinaryWriter()) {
        if (message.lowEdge !== undefined) {
            writer.uint32(9).double(message.lowEdge);
        }
        if (message.increment !== undefined) {
            writer.uint32(17).double(message.increment);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBasePriceIncrement();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 9) {
                        break;
                    }
                    message.lowEdge = reader.double();
                    continue;
                }
                case 2: {
                    if (tag !== 17) {
                        break;
                    }
                    message.increment = reader.double();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            lowEdge: isSet(object.lowEdge) ? globalThis.Number(object.lowEdge) : undefined,
            increment: isSet(object.increment) ? globalThis.Number(object.increment) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.lowEdge !== undefined) {
            obj.lowEdge = message.lowEdge;
        }
        if (message.increment !== undefined) {
            obj.increment = message.increment;
        }
        return obj;
    },
    create(base) {
        return PriceIncrement.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBasePriceIncrement();
        message.lowEdge = object.lowEdge ?? undefined;
        message.increment = object.increment ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=PriceIncrement.js.map