// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: ScannerData.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { ScannerDataElement } from "./ScannerDataElement.js";
export const protobufPackage = "protobuf";
function createBaseScannerData() {
    return { reqId: undefined, scannerDataElement: [] };
}
export const ScannerData = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        for (const v of message.scannerDataElement) {
            ScannerDataElement.encode(v, writer.uint32(18).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseScannerData();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.scannerDataElement.push(ScannerDataElement.decode(reader, reader.uint32()));
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            scannerDataElement: globalThis.Array.isArray(object?.scannerDataElement)
                ? object.scannerDataElement.map((e) => ScannerDataElement.fromJSON(e))
                : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.scannerDataElement?.length) {
            obj.scannerDataElement = message.scannerDataElement.map((e) => ScannerDataElement.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return ScannerData.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseScannerData();
        message.reqId = object.reqId ?? undefined;
        message.scannerDataElement = object.scannerDataElement?.map((e) => ScannerDataElement.fromPartial(e)) || [];
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=ScannerData.js.map