// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: ScannerSubscriptionRequest.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { ScannerSubscription } from "./ScannerSubscription.js";
export const protobufPackage = "protobuf";
function createBaseScannerSubscriptionRequest() {
    return { reqId: undefined, scannerSubscription: undefined };
}
export const ScannerSubscriptionRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        if (message.scannerSubscription !== undefined) {
            ScannerSubscription.encode(message.scannerSubscription, writer.uint32(18).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseScannerSubscriptionRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.scannerSubscription = ScannerSubscription.decode(reader, reader.uint32());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            scannerSubscription: isSet(object.scannerSubscription)
                ? ScannerSubscription.fromJSON(object.scannerSubscription)
                : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.scannerSubscription !== undefined) {
            obj.scannerSubscription = ScannerSubscription.toJSON(message.scannerSubscription);
        }
        return obj;
    },
    create(base) {
        return ScannerSubscriptionRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseScannerSubscriptionRequest();
        message.reqId = object.reqId ?? undefined;
        message.scannerSubscription = (object.scannerSubscription !== undefined && object.scannerSubscription !== null)
            ? ScannerSubscription.fromPartial(object.scannerSubscription)
            : undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=ScannerSubscriptionRequest.js.map