// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: ScannerParameters.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseScannerParameters() {
    return { xml: undefined };
}
export const ScannerParameters = {
    encode(message, writer = new BinaryWriter()) {
        if (message.xml !== undefined) {
            writer.uint32(10).string(message.xml);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseScannerParameters();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.xml = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { xml: isSet(object.xml) ? globalThis.String(object.xml) : undefined };
    },
    toJSON(message) {
        const obj = {};
        if (message.xml !== undefined) {
            obj.xml = message.xml;
        }
        return obj;
    },
    create(base) {
        return ScannerParameters.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseScannerParameters();
        message.xml = object.xml ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=ScannerParameters.js.map