// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: SecDefOptParamsRequest.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseSecDefOptParamsRequest() {
    return {
        reqId: undefined,
        underlyingSymbol: undefined,
        futFopExchange: undefined,
        underlyingSecType: undefined,
        underlyingConId: undefined,
    };
}
export const SecDefOptParamsRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        if (message.underlyingSymbol !== undefined) {
            writer.uint32(18).string(message.underlyingSymbol);
        }
        if (message.futFopExchange !== undefined) {
            writer.uint32(26).string(message.futFopExchange);
        }
        if (message.underlyingSecType !== undefined) {
            writer.uint32(34).string(message.underlyingSecType);
        }
        if (message.underlyingConId !== undefined) {
            writer.uint32(40).int32(message.underlyingConId);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSecDefOptParamsRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.underlyingSymbol = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.futFopExchange = reader.string();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.underlyingSecType = reader.string();
                    continue;
                }
                case 5: {
                    if (tag !== 40) {
                        break;
                    }
                    message.underlyingConId = reader.int32();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            underlyingSymbol: isSet(object.underlyingSymbol) ? globalThis.String(object.underlyingSymbol) : undefined,
            futFopExchange: isSet(object.futFopExchange) ? globalThis.String(object.futFopExchange) : undefined,
            underlyingSecType: isSet(object.underlyingSecType) ? globalThis.String(object.underlyingSecType) : undefined,
            underlyingConId: isSet(object.underlyingConId) ? globalThis.Number(object.underlyingConId) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.underlyingSymbol !== undefined) {
            obj.underlyingSymbol = message.underlyingSymbol;
        }
        if (message.futFopExchange !== undefined) {
            obj.futFopExchange = message.futFopExchange;
        }
        if (message.underlyingSecType !== undefined) {
            obj.underlyingSecType = message.underlyingSecType;
        }
        if (message.underlyingConId !== undefined) {
            obj.underlyingConId = Math.round(message.underlyingConId);
        }
        return obj;
    },
    create(base) {
        return SecDefOptParamsRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSecDefOptParamsRequest();
        message.reqId = object.reqId ?? undefined;
        message.underlyingSymbol = object.underlyingSymbol ?? undefined;
        message.futFopExchange = object.futFopExchange ?? undefined;
        message.underlyingSecType = object.underlyingSecType ?? undefined;
        message.underlyingConId = object.underlyingConId ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=SecDefOptParamsRequest.js.map