// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: SmartComponent.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseSmartComponent() {
    return { bitNumber: undefined, exchange: undefined, exchangeLetter: undefined };
}
export const SmartComponent = {
    encode(message, writer = new BinaryWriter()) {
        if (message.bitNumber !== undefined) {
            writer.uint32(8).int32(message.bitNumber);
        }
        if (message.exchange !== undefined) {
            writer.uint32(18).string(message.exchange);
        }
        if (message.exchangeLetter !== undefined) {
            writer.uint32(26).string(message.exchangeLetter);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSmartComponent();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.bitNumber = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.exchange = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.exchangeLetter = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            bitNumber: isSet(object.bitNumber) ? globalThis.Number(object.bitNumber) : undefined,
            exchange: isSet(object.exchange) ? globalThis.String(object.exchange) : undefined,
            exchangeLetter: isSet(object.exchangeLetter) ? globalThis.String(object.exchangeLetter) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.bitNumber !== undefined) {
            obj.bitNumber = Math.round(message.bitNumber);
        }
        if (message.exchange !== undefined) {
            obj.exchange = message.exchange;
        }
        if (message.exchangeLetter !== undefined) {
            obj.exchangeLetter = message.exchangeLetter;
        }
        return obj;
    },
    create(base) {
        return SmartComponent.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSmartComponent();
        message.bitNumber = object.bitNumber ?? undefined;
        message.exchange = object.exchange ?? undefined;
        message.exchangeLetter = object.exchangeLetter ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=SmartComponent.js.map