// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: SmartComponents.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { SmartComponent } from "./SmartComponent.js";
export const protobufPackage = "protobuf";
function createBaseSmartComponents() {
    return { reqId: undefined, smartComponents: [] };
}
export const SmartComponents = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        for (const v of message.smartComponents) {
            SmartComponent.encode(v, writer.uint32(18).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSmartComponents();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.smartComponents.push(SmartComponent.decode(reader, reader.uint32()));
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            smartComponents: globalThis.Array.isArray(object?.smartComponents)
                ? object.smartComponents.map((e) => SmartComponent.fromJSON(e))
                : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.smartComponents?.length) {
            obj.smartComponents = message.smartComponents.map((e) => SmartComponent.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return SmartComponents.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSmartComponents();
        message.reqId = object.reqId ?? undefined;
        message.smartComponents = object.smartComponents?.map((e) => SmartComponent.fromPartial(e)) || [];
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=SmartComponents.js.map