// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: SoftDollarTiers.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { SoftDollarTier } from "./SoftDollarTier.js";
export const protobufPackage = "protobuf";
function createBaseSoftDollarTiers() {
    return { reqId: undefined, softDollarTiers: [] };
}
export const SoftDollarTiers = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        for (const v of message.softDollarTiers) {
            SoftDollarTier.encode(v, writer.uint32(18).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSoftDollarTiers();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.softDollarTiers.push(SoftDollarTier.decode(reader, reader.uint32()));
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            softDollarTiers: globalThis.Array.isArray(object?.softDollarTiers)
                ? object.softDollarTiers.map((e) => SoftDollarTier.fromJSON(e))
                : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.softDollarTiers?.length) {
            obj.softDollarTiers = message.softDollarTiers.map((e) => SoftDollarTier.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return SoftDollarTiers.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSoftDollarTiers();
        message.reqId = object.reqId ?? undefined;
        message.softDollarTiers = object.softDollarTiers?.map((e) => SoftDollarTier.fromPartial(e)) || [];
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=SoftDollarTiers.js.map