// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: StartApiRequest.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseStartApiRequest() {
    return { clientId: undefined, optionalCapabilities: undefined };
}
export const StartApiRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.clientId !== undefined) {
            writer.uint32(8).int32(message.clientId);
        }
        if (message.optionalCapabilities !== undefined) {
            writer.uint32(18).string(message.optionalCapabilities);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseStartApiRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.clientId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.optionalCapabilities = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            clientId: isSet(object.clientId) ? globalThis.Number(object.clientId) : undefined,
            optionalCapabilities: isSet(object.optionalCapabilities)
                ? globalThis.String(object.optionalCapabilities)
                : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.clientId !== undefined) {
            obj.clientId = Math.round(message.clientId);
        }
        if (message.optionalCapabilities !== undefined) {
            obj.optionalCapabilities = message.optionalCapabilities;
        }
        return obj;
    },
    create(base) {
        return StartApiRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseStartApiRequest();
        message.clientId = object.clientId ?? undefined;
        message.optionalCapabilities = object.optionalCapabilities ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=StartApiRequest.js.map