// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: SymbolSamples.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { ContractDescription } from "./ContractDescription.js";
export const protobufPackage = "protobuf";
function createBaseSymbolSamples() {
    return { reqId: undefined, contractDescriptions: [] };
}
export const SymbolSamples = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        for (const v of message.contractDescriptions) {
            ContractDescription.encode(v, writer.uint32(18).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseSymbolSamples();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.contractDescriptions.push(ContractDescription.decode(reader, reader.uint32()));
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            contractDescriptions: globalThis.Array.isArray(object?.contractDescriptions)
                ? object.contractDescriptions.map((e) => ContractDescription.fromJSON(e))
                : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.contractDescriptions?.length) {
            obj.contractDescriptions = message.contractDescriptions.map((e) => ContractDescription.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return SymbolSamples.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSymbolSamples();
        message.reqId = object.reqId ?? undefined;
        message.contractDescriptions = object.contractDescriptions?.map((e) => ContractDescription.fromPartial(e)) || [];
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=SymbolSamples.js.map