// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: TickAttribLast.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseTickAttribLast() {
    return { pastLimit: undefined, unreported: undefined };
}
export const TickAttribLast = {
    encode(message, writer = new BinaryWriter()) {
        if (message.pastLimit !== undefined) {
            writer.uint32(8).bool(message.pastLimit);
        }
        if (message.unreported !== undefined) {
            writer.uint32(16).bool(message.unreported);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseTickAttribLast();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.pastLimit = reader.bool();
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.unreported = reader.bool();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            pastLimit: isSet(object.pastLimit) ? globalThis.Boolean(object.pastLimit) : undefined,
            unreported: isSet(object.unreported) ? globalThis.Boolean(object.unreported) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.pastLimit !== undefined) {
            obj.pastLimit = message.pastLimit;
        }
        if (message.unreported !== undefined) {
            obj.unreported = message.unreported;
        }
        return obj;
    },
    create(base) {
        return TickAttribLast.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseTickAttribLast();
        message.pastLimit = object.pastLimit ?? undefined;
        message.unreported = object.unreported ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=TickAttribLast.js.map