// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: TickAttribBidAsk.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseTickAttribBidAsk() {
    return { bidPastLow: undefined, askPastHigh: undefined };
}
export const TickAttribBidAsk = {
    encode(message, writer = new BinaryWriter()) {
        if (message.bidPastLow !== undefined) {
            writer.uint32(8).bool(message.bidPastLow);
        }
        if (message.askPastHigh !== undefined) {
            writer.uint32(16).bool(message.askPastHigh);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseTickAttribBidAsk();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.bidPastLow = reader.bool();
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.askPastHigh = reader.bool();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            bidPastLow: isSet(object.bidPastLow) ? globalThis.Boolean(object.bidPastLow) : undefined,
            askPastHigh: isSet(object.askPastHigh) ? globalThis.Boolean(object.askPastHigh) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.bidPastLow !== undefined) {
            obj.bidPastLow = message.bidPastLow;
        }
        if (message.askPastHigh !== undefined) {
            obj.askPastHigh = message.askPastHigh;
        }
        return obj;
    },
    create(base) {
        return TickAttribBidAsk.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseTickAttribBidAsk();
        message.bidPastLow = object.bidPastLow ?? undefined;
        message.askPastHigh = object.askPastHigh ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=TickAttribBidAsk.js.map