// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: TickByTickRequest.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Contract } from "./Contract.js";
export const protobufPackage = "protobuf";
function createBaseTickByTickRequest() {
    return {
        reqId: undefined,
        contract: undefined,
        tickType: undefined,
        numberOfTicks: undefined,
        ignoreSize: undefined,
    };
}
export const TickByTickRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        if (message.contract !== undefined) {
            Contract.encode(message.contract, writer.uint32(18).fork()).join();
        }
        if (message.tickType !== undefined) {
            writer.uint32(26).string(message.tickType);
        }
        if (message.numberOfTicks !== undefined) {
            writer.uint32(32).int32(message.numberOfTicks);
        }
        if (message.ignoreSize !== undefined) {
            writer.uint32(40).bool(message.ignoreSize);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseTickByTickRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.contract = Contract.decode(reader, reader.uint32());
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.tickType = reader.string();
                    continue;
                }
                case 4: {
                    if (tag !== 32) {
                        break;
                    }
                    message.numberOfTicks = reader.int32();
                    continue;
                }
                case 5: {
                    if (tag !== 40) {
                        break;
                    }
                    message.ignoreSize = reader.bool();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            contract: isSet(object.contract) ? Contract.fromJSON(object.contract) : undefined,
            tickType: isSet(object.tickType) ? globalThis.String(object.tickType) : undefined,
            numberOfTicks: isSet(object.numberOfTicks) ? globalThis.Number(object.numberOfTicks) : undefined,
            ignoreSize: isSet(object.ignoreSize) ? globalThis.Boolean(object.ignoreSize) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.contract !== undefined) {
            obj.contract = Contract.toJSON(message.contract);
        }
        if (message.tickType !== undefined) {
            obj.tickType = message.tickType;
        }
        if (message.numberOfTicks !== undefined) {
            obj.numberOfTicks = Math.round(message.numberOfTicks);
        }
        if (message.ignoreSize !== undefined) {
            obj.ignoreSize = message.ignoreSize;
        }
        return obj;
    },
    create(base) {
        return TickByTickRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseTickByTickRequest();
        message.reqId = object.reqId ?? undefined;
        message.contract = (object.contract !== undefined && object.contract !== null)
            ? Contract.fromPartial(object.contract)
            : undefined;
        message.tickType = object.tickType ?? undefined;
        message.numberOfTicks = object.numberOfTicks ?? undefined;
        message.ignoreSize = object.ignoreSize ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=TickByTickRequest.js.map