// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: TickPrice.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseTickPrice() {
    return { reqId: undefined, tickType: undefined, price: undefined, size: undefined, attrMask: undefined };
}
export const TickPrice = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        if (message.tickType !== undefined) {
            writer.uint32(16).int32(message.tickType);
        }
        if (message.price !== undefined) {
            writer.uint32(25).double(message.price);
        }
        if (message.size !== undefined) {
            writer.uint32(34).string(message.size);
        }
        if (message.attrMask !== undefined) {
            writer.uint32(40).int32(message.attrMask);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseTickPrice();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.tickType = reader.int32();
                    continue;
                }
                case 3: {
                    if (tag !== 25) {
                        break;
                    }
                    message.price = reader.double();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.size = reader.string();
                    continue;
                }
                case 5: {
                    if (tag !== 40) {
                        break;
                    }
                    message.attrMask = reader.int32();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            tickType: isSet(object.tickType) ? globalThis.Number(object.tickType) : undefined,
            price: isSet(object.price) ? globalThis.Number(object.price) : undefined,
            size: isSet(object.size) ? globalThis.String(object.size) : undefined,
            attrMask: isSet(object.attrMask) ? globalThis.Number(object.attrMask) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.tickType !== undefined) {
            obj.tickType = Math.round(message.tickType);
        }
        if (message.price !== undefined) {
            obj.price = message.price;
        }
        if (message.size !== undefined) {
            obj.size = message.size;
        }
        if (message.attrMask !== undefined) {
            obj.attrMask = Math.round(message.attrMask);
        }
        return obj;
    },
    create(base) {
        return TickPrice.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseTickPrice();
        message.reqId = object.reqId ?? undefined;
        message.tickType = object.tickType ?? undefined;
        message.price = object.price ?? undefined;
        message.size = object.size ?? undefined;
        message.attrMask = object.attrMask ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=TickPrice.js.map