// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: UpdateConfigResponse.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { UpdateConfigWarning } from "./UpdateConfigWarning.js";
export const protobufPackage = "protobuf";
function createBaseUpdateConfigResponse() {
    return { reqId: undefined, status: undefined, message: undefined, changedFields: [], errors: [], warnings: [] };
}
export const UpdateConfigResponse = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reqId !== undefined) {
            writer.uint32(8).int32(message.reqId);
        }
        if (message.status !== undefined) {
            writer.uint32(18).string(message.status);
        }
        if (message.message !== undefined) {
            writer.uint32(26).string(message.message);
        }
        for (const v of message.changedFields) {
            writer.uint32(34).string(v);
        }
        for (const v of message.errors) {
            writer.uint32(42).string(v);
        }
        for (const v of message.warnings) {
            UpdateConfigWarning.encode(v, writer.uint32(50).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseUpdateConfigResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.reqId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.status = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.message = reader.string();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.changedFields.push(reader.string());
                    continue;
                }
                case 5: {
                    if (tag !== 42) {
                        break;
                    }
                    message.errors.push(reader.string());
                    continue;
                }
                case 6: {
                    if (tag !== 50) {
                        break;
                    }
                    message.warnings.push(UpdateConfigWarning.decode(reader, reader.uint32()));
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            reqId: isSet(object.reqId) ? globalThis.Number(object.reqId) : undefined,
            status: isSet(object.status) ? globalThis.String(object.status) : undefined,
            message: isSet(object.message) ? globalThis.String(object.message) : undefined,
            changedFields: globalThis.Array.isArray(object?.changedFields)
                ? object.changedFields.map((e) => globalThis.String(e))
                : [],
            errors: globalThis.Array.isArray(object?.errors) ? object.errors.map((e) => globalThis.String(e)) : [],
            warnings: globalThis.Array.isArray(object?.warnings)
                ? object.warnings.map((e) => UpdateConfigWarning.fromJSON(e))
                : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reqId !== undefined) {
            obj.reqId = Math.round(message.reqId);
        }
        if (message.status !== undefined) {
            obj.status = message.status;
        }
        if (message.message !== undefined) {
            obj.message = message.message;
        }
        if (message.changedFields?.length) {
            obj.changedFields = message.changedFields;
        }
        if (message.errors?.length) {
            obj.errors = message.errors;
        }
        if (message.warnings?.length) {
            obj.warnings = message.warnings.map((e) => UpdateConfigWarning.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return UpdateConfigResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseUpdateConfigResponse();
        message.reqId = object.reqId ?? undefined;
        message.status = object.status ?? undefined;
        message.message = object.message ?? undefined;
        message.changedFields = object.changedFields?.map((e) => e) || [];
        message.errors = object.errors?.map((e) => e) || [];
        message.warnings = object.warnings?.map((e) => UpdateConfigWarning.fromPartial(e)) || [];
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=UpdateConfigResponse.js.map