// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: UpdateConfigWarning.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseUpdateConfigWarning() {
    return { messageId: undefined, title: undefined, message: undefined };
}
export const UpdateConfigWarning = {
    encode(message, writer = new BinaryWriter()) {
        if (message.messageId !== undefined) {
            writer.uint32(8).int32(message.messageId);
        }
        if (message.title !== undefined) {
            writer.uint32(18).string(message.title);
        }
        if (message.message !== undefined) {
            writer.uint32(26).string(message.message);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseUpdateConfigWarning();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.messageId = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.title = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.message = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            messageId: isSet(object.messageId) ? globalThis.Number(object.messageId) : undefined,
            title: isSet(object.title) ? globalThis.String(object.title) : undefined,
            message: isSet(object.message) ? globalThis.String(object.message) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.messageId !== undefined) {
            obj.messageId = Math.round(message.messageId);
        }
        if (message.title !== undefined) {
            obj.title = message.title;
        }
        if (message.message !== undefined) {
            obj.message = message.message;
        }
        return obj;
    },
    create(base) {
        return UpdateConfigWarning.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseUpdateConfigWarning();
        message.messageId = object.messageId ?? undefined;
        message.title = object.title ?? undefined;
        message.message = object.message ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=UpdateConfigWarning.js.map