// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: VerifyMessageApi.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseVerifyMessageApi() {
    return { apiData: undefined };
}
export const VerifyMessageApi = {
    encode(message, writer = new BinaryWriter()) {
        if (message.apiData !== undefined) {
            writer.uint32(10).string(message.apiData);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseVerifyMessageApi();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.apiData = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return { apiData: isSet(object.apiData) ? globalThis.String(object.apiData) : undefined };
    },
    toJSON(message) {
        const obj = {};
        if (message.apiData !== undefined) {
            obj.apiData = message.apiData;
        }
        return obj;
    },
    create(base) {
        return VerifyMessageApi.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseVerifyMessageApi();
        message.apiData = object.apiData ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=VerifyMessageApi.js.map