// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: VerifyRequest.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseVerifyRequest() {
    return { apiName: undefined, apiVersion: undefined };
}
export const VerifyRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.apiName !== undefined) {
            writer.uint32(10).string(message.apiName);
        }
        if (message.apiVersion !== undefined) {
            writer.uint32(18).string(message.apiVersion);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseVerifyRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.apiName = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.apiVersion = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            apiName: isSet(object.apiName) ? globalThis.String(object.apiName) : undefined,
            apiVersion: isSet(object.apiVersion) ? globalThis.String(object.apiVersion) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.apiName !== undefined) {
            obj.apiName = message.apiName;
        }
        if (message.apiVersion !== undefined) {
            obj.apiVersion = message.apiVersion;
        }
        return obj;
    },
    create(base) {
        return VerifyRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseVerifyRequest();
        message.apiName = object.apiName ?? undefined;
        message.apiVersion = object.apiVersion ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=VerifyRequest.js.map