// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.1
// source: VerifyCompleted.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "protobuf";
function createBaseVerifyCompleted() {
    return { isSuccessful: undefined, errorText: undefined };
}
export const VerifyCompleted = {
    encode(message, writer = new BinaryWriter()) {
        if (message.isSuccessful !== undefined) {
            writer.uint32(8).bool(message.isSuccessful);
        }
        if (message.errorText !== undefined) {
            writer.uint32(18).string(message.errorText);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseVerifyCompleted();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.isSuccessful = reader.bool();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.errorText = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            isSuccessful: isSet(object.isSuccessful) ? globalThis.Boolean(object.isSuccessful) : undefined,
            errorText: isSet(object.errorText) ? globalThis.String(object.errorText) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.isSuccessful !== undefined) {
            obj.isSuccessful = message.isSuccessful;
        }
        if (message.errorText !== undefined) {
            obj.errorText = message.errorText;
        }
        return obj;
    },
    create(base) {
        return VerifyCompleted.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseVerifyCompleted();
        message.isSuccessful = object.isSuccessful ?? undefined;
        message.errorText = object.errorText ?? undefined;
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=VerifyCompleted.js.map