/**
 * FMP Balance Sheet Growth Model.
 * Maps to: openbb_fmp/models/balance_sheet_growth.py
 */
import { z } from 'zod';
import { Fetcher } from '../../../core/provider/abstract/fetcher.js';
export declare const FMPBalanceSheetGrowthQueryParamsSchema: z.ZodObject<{
    symbol: z.ZodEffects<z.ZodString, string, string>;
} & {
    period: z.ZodDefault<z.ZodEnum<["annual", "quarter"]>>;
    limit: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
}, "strip", z.ZodTypeAny, {
    symbol: string;
    limit: number | null;
    period: "annual" | "quarter";
}, {
    symbol: string;
    limit?: number | null | undefined;
    period?: "annual" | "quarter" | undefined;
}>;
export type FMPBalanceSheetGrowthQueryParams = z.infer<typeof FMPBalanceSheetGrowthQueryParamsSchema>;
export declare const FMPBalanceSheetGrowthDataSchema: z.ZodObject<{
    period_ending: z.ZodString;
    fiscal_period: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    fiscal_year: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
} & {
    symbol: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    reported_currency: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    growth_cash_and_cash_equivalents: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_short_term_investments: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_cash_and_short_term_investments: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_accounts_receivables: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_other_receivables: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_net_receivables: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_inventory: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_other_current_assets: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_current_assets: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_property_plant_equipment_net: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_goodwill: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_intangible_assets: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_goodwill_and_intangible_assets: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_long_term_investments: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_tax_assets: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_other_non_current_assets: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_non_current_assets: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_other_assets: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_assets: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_account_payables: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_other_payables: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_payables: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_accrued_expenses: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_prepaid_expenses: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_capital_lease_obligations_current: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_short_term_debt: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_tax_payables: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_deferred_tax_liabilities_non_current: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_deferred_revenue: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_other_current_liabilities: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_current_liabilities: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_deferred_revenue_non_current: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_long_term_debt: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_deferrred_tax_liabilities_non_current: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_other_non_current_liabilities: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_non_current_liabilities: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_other_liabilities: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_liabilities: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_retained_earnings: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_accumulated_other_comprehensive_income: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_minority_interest: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_additional_paid_in_capital: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_other_total_shareholders_equity: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_shareholders_equity: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_common_stock: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_preferred_stock: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_treasury_stock: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_equity: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_liabilities_and_shareholders_equity: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_investments: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_debt: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_net_debt: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
}, "passthrough", z.ZodTypeAny, z.objectOutputType<{
    period_ending: z.ZodString;
    fiscal_period: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    fiscal_year: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
} & {
    symbol: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    reported_currency: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    growth_cash_and_cash_equivalents: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_short_term_investments: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_cash_and_short_term_investments: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_accounts_receivables: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_other_receivables: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_net_receivables: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_inventory: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_other_current_assets: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_current_assets: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_property_plant_equipment_net: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_goodwill: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_intangible_assets: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_goodwill_and_intangible_assets: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_long_term_investments: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_tax_assets: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_other_non_current_assets: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_non_current_assets: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_other_assets: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_assets: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_account_payables: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_other_payables: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_payables: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_accrued_expenses: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_prepaid_expenses: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_capital_lease_obligations_current: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_short_term_debt: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_tax_payables: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_deferred_tax_liabilities_non_current: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_deferred_revenue: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_other_current_liabilities: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_current_liabilities: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_deferred_revenue_non_current: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_long_term_debt: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_deferrred_tax_liabilities_non_current: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_other_non_current_liabilities: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_non_current_liabilities: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_other_liabilities: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_liabilities: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_retained_earnings: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_accumulated_other_comprehensive_income: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_minority_interest: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_additional_paid_in_capital: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_other_total_shareholders_equity: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_shareholders_equity: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_common_stock: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_preferred_stock: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_treasury_stock: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_equity: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_liabilities_and_shareholders_equity: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_investments: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_debt: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_net_debt: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
}, z.ZodTypeAny, "passthrough">, z.objectInputType<{
    period_ending: z.ZodString;
    fiscal_period: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    fiscal_year: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
} & {
    symbol: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    reported_currency: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    growth_cash_and_cash_equivalents: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_short_term_investments: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_cash_and_short_term_investments: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_accounts_receivables: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_other_receivables: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_net_receivables: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_inventory: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_other_current_assets: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_current_assets: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_property_plant_equipment_net: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_goodwill: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_intangible_assets: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_goodwill_and_intangible_assets: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_long_term_investments: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_tax_assets: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_other_non_current_assets: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_non_current_assets: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_other_assets: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_assets: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_account_payables: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_other_payables: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_payables: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_accrued_expenses: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_prepaid_expenses: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_capital_lease_obligations_current: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_short_term_debt: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_tax_payables: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_deferred_tax_liabilities_non_current: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_deferred_revenue: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_other_current_liabilities: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_current_liabilities: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_deferred_revenue_non_current: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_long_term_debt: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_deferrred_tax_liabilities_non_current: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_other_non_current_liabilities: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_non_current_liabilities: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_other_liabilities: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_liabilities: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_retained_earnings: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_accumulated_other_comprehensive_income: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_minority_interest: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_additional_paid_in_capital: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_other_total_shareholders_equity: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_shareholders_equity: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_common_stock: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_preferred_stock: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_treasury_stock: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_equity: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_liabilities_and_shareholders_equity: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_investments: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_total_debt: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    growth_net_debt: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
}, z.ZodTypeAny, "passthrough">>;
export type FMPBalanceSheetGrowthData = z.infer<typeof FMPBalanceSheetGrowthDataSchema>;
export declare class FMPBalanceSheetGrowthFetcher extends Fetcher {
    static transformQuery(params: Record<string, unknown>): FMPBalanceSheetGrowthQueryParams;
    static extractData(query: FMPBalanceSheetGrowthQueryParams, credentials: Record<string, string> | null): Promise<Record<string, unknown>[]>;
    static transformData(query: FMPBalanceSheetGrowthQueryParams, data: Record<string, unknown>[]): FMPBalanceSheetGrowthData[];
}
