/**
 * FMP Equity Profile Model.
 * Maps to: openbb_fmp/models/equity_profile.py
 */
import { z } from 'zod';
import { Fetcher } from '../../../core/provider/abstract/fetcher.js';
export declare const FMPEquityProfileQueryParamsSchema: z.ZodObject<{
    symbol: z.ZodEffects<z.ZodString, string, string>;
}, "passthrough", z.ZodTypeAny, z.objectOutputType<{
    symbol: z.ZodEffects<z.ZodString, string, string>;
}, z.ZodTypeAny, "passthrough">, z.objectInputType<{
    symbol: z.ZodEffects<z.ZodString, string, string>;
}, z.ZodTypeAny, "passthrough">>;
export type FMPEquityProfileQueryParams = z.infer<typeof FMPEquityProfileQueryParamsSchema>;
export declare const FMPEquityProfileDataSchema: z.ZodObject<{
    symbol: z.ZodString;
    name: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    cik: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    cusip: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    isin: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    lei: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    legal_name: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    stock_exchange: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    sic: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    short_description: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    long_description: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    ceo: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    company_url: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    business_address: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    mailing_address: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    business_phone_no: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    hq_address1: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    hq_address2: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    hq_address_city: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    hq_address_postal_code: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    hq_state: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    hq_country: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    inc_state: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    inc_country: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    employees: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    entity_legal_form: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    entity_status: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    latest_filing_date: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    irs_number: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    sector: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    industry_category: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    industry_group: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    template: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    standardized_active: z.ZodDefault<z.ZodNullable<z.ZodBoolean>>;
    first_fundamental_date: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    last_fundamental_date: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    first_stock_price_date: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    last_stock_price_date: z.ZodDefault<z.ZodNullable<z.ZodString>>;
} & {
    is_etf: z.ZodDefault<z.ZodBoolean>;
    is_actively_trading: z.ZodDefault<z.ZodBoolean>;
    is_adr: z.ZodDefault<z.ZodBoolean>;
    is_fund: z.ZodDefault<z.ZodBoolean>;
    image: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    currency: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    market_cap: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    last_price: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    year_high: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    year_low: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    volume_avg: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    annualized_dividend_amount: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    beta: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
}, "strip", z.ZodTypeAny, {
    symbol: string;
    name: string | null;
    currency: string | null;
    cusip: string | null;
    cik: string | null;
    isin: string | null;
    lei: string | null;
    legal_name: string | null;
    stock_exchange: string | null;
    sic: number | null;
    short_description: string | null;
    long_description: string | null;
    ceo: string | null;
    company_url: string | null;
    business_address: string | null;
    mailing_address: string | null;
    business_phone_no: string | null;
    hq_address1: string | null;
    hq_address2: string | null;
    hq_address_city: string | null;
    hq_address_postal_code: string | null;
    hq_state: string | null;
    hq_country: string | null;
    inc_state: string | null;
    inc_country: string | null;
    employees: number | null;
    entity_legal_form: string | null;
    entity_status: string | null;
    latest_filing_date: string | null;
    irs_number: string | null;
    sector: string | null;
    industry_category: string | null;
    industry_group: string | null;
    template: string | null;
    standardized_active: boolean | null;
    first_fundamental_date: string | null;
    last_fundamental_date: string | null;
    first_stock_price_date: string | null;
    last_stock_price_date: string | null;
    last_price: number | null;
    volume_avg: number | null;
    annualized_dividend_amount: number | null;
    is_etf: boolean;
    is_actively_trading: boolean;
    is_adr: boolean;
    is_fund: boolean;
    image: string | null;
    market_cap: number | null;
    year_high: number | null;
    year_low: number | null;
    beta: number | null;
}, {
    symbol: string;
    name?: string | null | undefined;
    currency?: string | null | undefined;
    cusip?: string | null | undefined;
    cik?: string | null | undefined;
    isin?: string | null | undefined;
    lei?: string | null | undefined;
    legal_name?: string | null | undefined;
    stock_exchange?: string | null | undefined;
    sic?: number | null | undefined;
    short_description?: string | null | undefined;
    long_description?: string | null | undefined;
    ceo?: string | null | undefined;
    company_url?: string | null | undefined;
    business_address?: string | null | undefined;
    mailing_address?: string | null | undefined;
    business_phone_no?: string | null | undefined;
    hq_address1?: string | null | undefined;
    hq_address2?: string | null | undefined;
    hq_address_city?: string | null | undefined;
    hq_address_postal_code?: string | null | undefined;
    hq_state?: string | null | undefined;
    hq_country?: string | null | undefined;
    inc_state?: string | null | undefined;
    inc_country?: string | null | undefined;
    employees?: number | null | undefined;
    entity_legal_form?: string | null | undefined;
    entity_status?: string | null | undefined;
    latest_filing_date?: string | null | undefined;
    irs_number?: string | null | undefined;
    sector?: string | null | undefined;
    industry_category?: string | null | undefined;
    industry_group?: string | null | undefined;
    template?: string | null | undefined;
    standardized_active?: boolean | null | undefined;
    first_fundamental_date?: string | null | undefined;
    last_fundamental_date?: string | null | undefined;
    first_stock_price_date?: string | null | undefined;
    last_stock_price_date?: string | null | undefined;
    last_price?: number | null | undefined;
    volume_avg?: number | null | undefined;
    annualized_dividend_amount?: number | null | undefined;
    is_etf?: boolean | undefined;
    is_actively_trading?: boolean | undefined;
    is_adr?: boolean | undefined;
    is_fund?: boolean | undefined;
    image?: string | null | undefined;
    market_cap?: number | null | undefined;
    year_high?: number | null | undefined;
    year_low?: number | null | undefined;
    beta?: number | null | undefined;
}>;
export type FMPEquityProfileData = z.infer<typeof FMPEquityProfileDataSchema>;
export declare class FMPEquityProfileFetcher extends Fetcher {
    static transformQuery(params: Record<string, unknown>): FMPEquityProfileQueryParams;
    static extractData(query: FMPEquityProfileQueryParams, credentials: Record<string, string> | null): Promise<Record<string, unknown>[]>;
    static transformData(query: FMPEquityProfileQueryParams, data: Record<string, unknown>[]): FMPEquityProfileData[];
}
